// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"
	"college-graduation-project-backend/internal/model/request"
	"college-graduation-project-backend/internal/model/response"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingService creates a new instance of MockBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingService {
	mock := &MockBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingService is an autogenerated mock type for the BookingService type
type MockBookingService struct {
	mock.Mock
}

type MockBookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingService) EXPECT() *MockBookingService_Expecter {
	return &MockBookingService_Expecter{mock: &_m.Mock}
}

// CalculatePrice provides a mock function for the type MockBookingService
func (_mock *MockBookingService) CalculatePrice(hallID uint64, from time.Time, to time.Time) (*response.CalculatedPrice, error) {
	ret := _mock.Called(hallID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CalculatePrice")
	}

	var r0 *response.CalculatedPrice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) (*response.CalculatedPrice, error)); ok {
		return returnFunc(hallID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) *response.CalculatedPrice); ok {
		r0 = returnFunc(hallID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CalculatedPrice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time) error); ok {
		r1 = returnFunc(hallID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_CalculatePrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculatePrice'
type MockBookingService_CalculatePrice_Call struct {
	*mock.Call
}

// CalculatePrice is a helper method to define mock.On call
//   - hallID uint64
//   - from time.Time
//   - to time.Time
func (_e *MockBookingService_Expecter) CalculatePrice(hallID interface{}, from interface{}, to interface{}) *MockBookingService_CalculatePrice_Call {
	return &MockBookingService_CalculatePrice_Call{Call: _e.mock.On("CalculatePrice", hallID, from, to)}
}

func (_c *MockBookingService_CalculatePrice_Call) Run(run func(hallID uint64, from time.Time, to time.Time)) *MockBookingService_CalculatePrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingService_CalculatePrice_Call) Return(calculatedPrice *response.CalculatedPrice, err error) *MockBookingService_CalculatePrice_Call {
	_c.Call.Return(calculatedPrice, err)
	return _c
}

func (_c *MockBookingService_CalculatePrice_Call) RunAndReturn(run func(hallID uint64, from time.Time, to time.Time) (*response.CalculatedPrice, error)) *MockBookingService_CalculatePrice_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingService
func (_mock *MockBookingService) Create(userID uint64, req *request.BookingCreate) (*model.Booking, error) {
	ret := _mock.Called(userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *request.BookingCreate) (*model.Booking, error)); ok {
		return returnFunc(userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *request.BookingCreate) *model.Booking); ok {
		r0 = returnFunc(userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *request.BookingCreate) error); ok {
		r1 = returnFunc(userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userID uint64
//   - req *request.BookingCreate
func (_e *MockBookingService_Expecter) Create(userID interface{}, req interface{}) *MockBookingService_Create_Call {
	return &MockBookingService_Create_Call{Call: _e.mock.On("Create", userID, req)}
}

func (_c *MockBookingService_Create_Call) Run(run func(userID uint64, req *request.BookingCreate)) *MockBookingService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *request.BookingCreate
		if args[1] != nil {
			arg1 = args[1].(*request.BookingCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingService_Create_Call) Return(booking *model.Booking, err error) *MockBookingService_Create_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingService_Create_Call) RunAndReturn(run func(userID uint64, req *request.BookingCreate) (*model.Booking, error)) *MockBookingService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByAuthor provides a mock function for the type MockBookingService
func (_mock *MockBookingService) DeleteByAuthor(userID uint64, id uint64) error {
	ret := _mock.Called(userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByAuthor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = returnFunc(userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingService_DeleteByAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByAuthor'
type MockBookingService_DeleteByAuthor_Call struct {
	*mock.Call
}

// DeleteByAuthor is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
func (_e *MockBookingService_Expecter) DeleteByAuthor(userID interface{}, id interface{}) *MockBookingService_DeleteByAuthor_Call {
	return &MockBookingService_DeleteByAuthor_Call{Call: _e.mock.On("DeleteByAuthor", userID, id)}
}

func (_c *MockBookingService_DeleteByAuthor_Call) Run(run func(userID uint64, id uint64)) *MockBookingService_DeleteByAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingService_DeleteByAuthor_Call) Return(err error) *MockBookingService_DeleteByAuthor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingService_DeleteByAuthor_Call) RunAndReturn(run func(userID uint64, id uint64) error) *MockBookingService_DeleteByAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockBookingService
func (_mock *MockBookingService) FindAll(userID uint64, hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time) ([]model.Booking, error) {
	ret := _mock.Called(userID, hallID, bookingUserID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *uint64, *uint64, *time.Time, *time.Time) ([]model.Booking, error)); ok {
		return returnFunc(userID, hallID, bookingUserID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *uint64, *uint64, *time.Time, *time.Time) []model.Booking); ok {
		r0 = returnFunc(userID, hallID, bookingUserID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *uint64, *uint64, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(userID, hallID, bookingUserID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBookingService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - userID uint64
//   - hallID *uint64
//   - bookingUserID *uint64
//   - from *time.Time
//   - to *time.Time
func (_e *MockBookingService_Expecter) FindAll(userID interface{}, hallID interface{}, bookingUserID interface{}, from interface{}, to interface{}) *MockBookingService_FindAll_Call {
	return &MockBookingService_FindAll_Call{Call: _e.mock.On("FindAll", userID, hallID, bookingUserID, from, to)}
}

func (_c *MockBookingService_FindAll_Call) Run(run func(userID uint64, hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time)) *MockBookingService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		var arg2 *uint64
		if args[2] != nil {
			arg2 = args[2].(*uint64)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBookingService_FindAll_Call) Return(bookings []model.Booking, err error) *MockBookingService_FindAll_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingService_FindAll_Call) RunAndReturn(run func(userID uint64, hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time) ([]model.Booking, error)) *MockBookingService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllFromUser provides a mock function for the type MockBookingService
func (_mock *MockBookingService) FindAllFromUser(userID uint64, from *time.Time, to *time.Time) ([]model.Booking, error) {
	ret := _mock.Called(userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindAllFromUser")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *time.Time, *time.Time) ([]model.Booking, error)); ok {
		return returnFunc(userID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *time.Time, *time.Time) []model.Booking); ok {
		r0 = returnFunc(userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(userID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_FindAllFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllFromUser'
type MockBookingService_FindAllFromUser_Call struct {
	*mock.Call
}

// FindAllFromUser is a helper method to define mock.On call
//   - userID uint64
//   - from *time.Time
//   - to *time.Time
func (_e *MockBookingService_Expecter) FindAllFromUser(userID interface{}, from interface{}, to interface{}) *MockBookingService_FindAllFromUser_Call {
	return &MockBookingService_FindAllFromUser_Call{Call: _e.mock.On("FindAllFromUser", userID, from, to)}
}

func (_c *MockBookingService_FindAllFromUser_Call) Run(run func(userID uint64, from *time.Time, to *time.Time)) *MockBookingService_FindAllFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingService_FindAllFromUser_Call) Return(bookings []model.Booking, err error) *MockBookingService_FindAllFromUser_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingService_FindAllFromUser_Call) RunAndReturn(run func(userID uint64, from *time.Time, to *time.Time) ([]model.Booking, error)) *MockBookingService_FindAllFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockBookingService
func (_mock *MockBookingService) FindByID(userID uint64, id uint64) (*model.Booking, error) {
	ret := _mock.Called(userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*model.Booking, error)); ok {
		return returnFunc(userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *model.Booking); ok {
		r0 = returnFunc(userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = returnFunc(userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBookingService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
func (_e *MockBookingService_Expecter) FindByID(userID interface{}, id interface{}) *MockBookingService_FindByID_Call {
	return &MockBookingService_FindByID_Call{Call: _e.mock.On("FindByID", userID, id)}
}

func (_c *MockBookingService_FindByID_Call) Run(run func(userID uint64, id uint64)) *MockBookingService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingService_FindByID_Call) Return(booking *model.Booking, err error) *MockBookingService_FindByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingService_FindByID_Call) RunAndReturn(run func(userID uint64, id uint64) (*model.Booking, error)) *MockBookingService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBookingService
func (_mock *MockBookingService) Update(userID uint64, id uint64, req *request.BookingUpdate) (*model.Booking, error) {
	ret := _mock.Called(userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.BookingUpdate) (*model.Booking, error)); ok {
		return returnFunc(userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.BookingUpdate) *model.Booking); ok {
		r0 = returnFunc(userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, *request.BookingUpdate) error); ok {
		r1 = returnFunc(userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBookingService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
//   - req *request.BookingUpdate
func (_e *MockBookingService_Expecter) Update(userID interface{}, id interface{}, req interface{}) *MockBookingService_Update_Call {
	return &MockBookingService_Update_Call{Call: _e.mock.On("Update", userID, id, req)}
}

func (_c *MockBookingService_Update_Call) Run(run func(userID uint64, id uint64, req *request.BookingUpdate)) *MockBookingService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *request.BookingUpdate
		if args[2] != nil {
			arg2 = args[2].(*request.BookingUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingService_Update_Call) Return(booking *model.Booking, err error) *MockBookingService_Update_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingService_Update_Call) RunAndReturn(run func(userID uint64, id uint64, req *request.BookingUpdate) (*model.Booking, error)) *MockBookingService_Update_Call {
	_c.Call.Return(run)
	return _c
}
