// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockImageDatabase creates a new instance of MockImageDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageDatabase {
	mock := &MockImageDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageDatabase is an autogenerated mock type for the ImageDatabase type
type MockImageDatabase struct {
	mock.Mock
}

type MockImageDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageDatabase) EXPECT() *MockImageDatabase_Expecter {
	return &MockImageDatabase_Expecter{mock: &_m.Mock}
}

// AttachToHall provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) AttachToHall(hallID uint64, imageID uint64) error {
	ret := _mock.Called(hallID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for AttachToHall")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = returnFunc(hallID, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_AttachToHall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachToHall'
type MockImageDatabase_AttachToHall_Call struct {
	*mock.Call
}

// AttachToHall is a helper method to define mock.On call
//   - hallID uint64
//   - imageID uint64
func (_e *MockImageDatabase_Expecter) AttachToHall(hallID interface{}, imageID interface{}) *MockImageDatabase_AttachToHall_Call {
	return &MockImageDatabase_AttachToHall_Call{Call: _e.mock.On("AttachToHall", hallID, imageID)}
}

func (_c *MockImageDatabase_AttachToHall_Call) Run(run func(hallID uint64, imageID uint64)) *MockImageDatabase_AttachToHall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageDatabase_AttachToHall_Call) Return(err error) *MockImageDatabase_AttachToHall_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_AttachToHall_Call) RunAndReturn(run func(hallID uint64, imageID uint64) error) *MockImageDatabase_AttachToHall_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) Create(image *model.Image) error {
	ret := _mock.Called(image)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Image) error); ok {
		r0 = returnFunc(image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockImageDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - image *model.Image
func (_e *MockImageDatabase_Expecter) Create(image interface{}) *MockImageDatabase_Create_Call {
	return &MockImageDatabase_Create_Call{Call: _e.mock.On("Create", image)}
}

func (_c *MockImageDatabase_Create_Call) Run(run func(image *model.Image)) *MockImageDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Image
		if args[0] != nil {
			arg0 = args[0].(*model.Image)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_Create_Call) Return(err error) *MockImageDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_Create_Call) RunAndReturn(run func(image *model.Image) error) *MockImageDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockImageDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockImageDatabase_Expecter) Delete(id interface{}) *MockImageDatabase_Delete_Call {
	return &MockImageDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockImageDatabase_Delete_Call) Run(run func(id uint64)) *MockImageDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_Delete_Call) Return(err error) *MockImageDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockImageDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHallID provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) FindByHallID(hallID uint64) ([]model.Image, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for FindByHallID")
	}

	var r0 []model.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) ([]model.Image, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) []model.Image); ok {
		r0 = returnFunc(hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageDatabase_FindByHallID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHallID'
type MockImageDatabase_FindByHallID_Call struct {
	*mock.Call
}

// FindByHallID is a helper method to define mock.On call
//   - hallID uint64
func (_e *MockImageDatabase_Expecter) FindByHallID(hallID interface{}) *MockImageDatabase_FindByHallID_Call {
	return &MockImageDatabase_FindByHallID_Call{Call: _e.mock.On("FindByHallID", hallID)}
}

func (_c *MockImageDatabase_FindByHallID_Call) Run(run func(hallID uint64)) *MockImageDatabase_FindByHallID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_FindByHallID_Call) Return(images []model.Image, err error) *MockImageDatabase_FindByHallID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageDatabase_FindByHallID_Call) RunAndReturn(run func(hallID uint64) ([]model.Image, error)) *MockImageDatabase_FindByHallID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) GetByID(id uint64) (*model.Image, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Image, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Image); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageDatabase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockImageDatabase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockImageDatabase_Expecter) GetByID(id interface{}) *MockImageDatabase_GetByID_Call {
	return &MockImageDatabase_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockImageDatabase_GetByID_Call) Run(run func(id uint64)) *MockImageDatabase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_GetByID_Call) Return(image *model.Image, err error) *MockImageDatabase_GetByID_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageDatabase_GetByID_Call) RunAndReturn(run func(id uint64) (*model.Image, error)) *MockImageDatabase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) GetByUserID(userID uint64) (*model.Image, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *model.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Image, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Image); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageDatabase_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockImageDatabase_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - userID uint64
func (_e *MockImageDatabase_Expecter) GetByUserID(userID interface{}) *MockImageDatabase_GetByUserID_Call {
	return &MockImageDatabase_GetByUserID_Call{Call: _e.mock.On("GetByUserID", userID)}
}

func (_c *MockImageDatabase_GetByUserID_Call) Run(run func(userID uint64)) *MockImageDatabase_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_GetByUserID_Call) Return(image *model.Image, err error) *MockImageDatabase_GetByUserID_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageDatabase_GetByUserID_Call) RunAndReturn(run func(userID uint64) (*model.Image, error)) *MockImageDatabase_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserImage provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) RemoveUserImage(userID uint64) error {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_RemoveUserImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserImage'
type MockImageDatabase_RemoveUserImage_Call struct {
	*mock.Call
}

// RemoveUserImage is a helper method to define mock.On call
//   - userID uint64
func (_e *MockImageDatabase_Expecter) RemoveUserImage(userID interface{}) *MockImageDatabase_RemoveUserImage_Call {
	return &MockImageDatabase_RemoveUserImage_Call{Call: _e.mock.On("RemoveUserImage", userID)}
}

func (_c *MockImageDatabase_RemoveUserImage_Call) Run(run func(userID uint64)) *MockImageDatabase_RemoveUserImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_RemoveUserImage_Call) Return(err error) *MockImageDatabase_RemoveUserImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_RemoveUserImage_Call) RunAndReturn(run func(userID uint64) error) *MockImageDatabase_RemoveUserImage_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserImage provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) SetUserImage(userID uint64, imageID uint64) error {
	ret := _mock.Called(userID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for SetUserImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = returnFunc(userID, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_SetUserImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserImage'
type MockImageDatabase_SetUserImage_Call struct {
	*mock.Call
}

// SetUserImage is a helper method to define mock.On call
//   - userID uint64
//   - imageID uint64
func (_e *MockImageDatabase_Expecter) SetUserImage(userID interface{}, imageID interface{}) *MockImageDatabase_SetUserImage_Call {
	return &MockImageDatabase_SetUserImage_Call{Call: _e.mock.On("SetUserImage", userID, imageID)}
}

func (_c *MockImageDatabase_SetUserImage_Call) Run(run func(userID uint64, imageID uint64)) *MockImageDatabase_SetUserImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageDatabase_SetUserImage_Call) Return(err error) *MockImageDatabase_SetUserImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_SetUserImage_Call) RunAndReturn(run func(userID uint64, imageID uint64) error) *MockImageDatabase_SetUserImage_Call {
	_c.Call.Return(run)
	return _c
}
