// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewDatabase creates a new instance of MockReviewDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewDatabase {
	mock := &MockReviewDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewDatabase is an autogenerated mock type for the ReviewDatabase type
type MockReviewDatabase struct {
	mock.Mock
}

type MockReviewDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewDatabase) EXPECT() *MockReviewDatabase_Expecter {
	return &MockReviewDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) Create(review *model.Review) error {
	ret := _mock.Called(review)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Review) error); ok {
		r0 = returnFunc(review)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReviewDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - review *model.Review
func (_e *MockReviewDatabase_Expecter) Create(review interface{}) *MockReviewDatabase_Create_Call {
	return &MockReviewDatabase_Create_Call{Call: _e.mock.On("Create", review)}
}

func (_c *MockReviewDatabase_Create_Call) Run(run func(review *model.Review)) *MockReviewDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Review
		if args[0] != nil {
			arg0 = args[0].(*model.Review)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_Create_Call) Return(err error) *MockReviewDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewDatabase_Create_Call) RunAndReturn(run func(review *model.Review) error) *MockReviewDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReviewDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockReviewDatabase_Expecter) Delete(id interface{}) *MockReviewDatabase_Delete_Call {
	return &MockReviewDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockReviewDatabase_Delete_Call) Run(run func(id uint64)) *MockReviewDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_Delete_Call) Return(err error) *MockReviewDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockReviewDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindAll() ([]model.Review, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Review, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Review); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockReviewDatabase_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockReviewDatabase_Expecter) FindAll() *MockReviewDatabase_FindAll_Call {
	return &MockReviewDatabase_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockReviewDatabase_FindAll_Call) Run(run func()) *MockReviewDatabase_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReviewDatabase_FindAll_Call) Return(reviews []model.Review, err error) *MockReviewDatabase_FindAll_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewDatabase_FindAll_Call) RunAndReturn(run func() ([]model.Review, error)) *MockReviewDatabase_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllWithFilters provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindAllWithFilters(hallID *uint64, minRating *uint64) ([]model.Review, error) {
	ret := _mock.Called(hallID, minRating)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithFilters")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) ([]model.Review, error)); ok {
		return returnFunc(hallID, minRating)
	}
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) []model.Review); ok {
		r0 = returnFunc(hallID, minRating)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*uint64, *uint64) error); ok {
		r1 = returnFunc(hallID, minRating)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindAllWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithFilters'
type MockReviewDatabase_FindAllWithFilters_Call struct {
	*mock.Call
}

// FindAllWithFilters is a helper method to define mock.On call
//   - hallID *uint64
//   - minRating *uint64
func (_e *MockReviewDatabase_Expecter) FindAllWithFilters(hallID interface{}, minRating interface{}) *MockReviewDatabase_FindAllWithFilters_Call {
	return &MockReviewDatabase_FindAllWithFilters_Call{Call: _e.mock.On("FindAllWithFilters", hallID, minRating)}
}

func (_c *MockReviewDatabase_FindAllWithFilters_Call) Run(run func(hallID *uint64, minRating *uint64)) *MockReviewDatabase_FindAllWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *uint64
		if args[0] != nil {
			arg0 = args[0].(*uint64)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindAllWithFilters_Call) Return(reviews []model.Review, err error) *MockReviewDatabase_FindAllWithFilters_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewDatabase_FindAllWithFilters_Call) RunAndReturn(run func(hallID *uint64, minRating *uint64) ([]model.Review, error)) *MockReviewDatabase_FindAllWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBookingID provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindByBookingID(bookingID uint64) (*model.Review, error) {
	ret := _mock.Called(bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBookingID")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Review, error)); ok {
		return returnFunc(bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Review); ok {
		r0 = returnFunc(bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindByBookingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBookingID'
type MockReviewDatabase_FindByBookingID_Call struct {
	*mock.Call
}

// FindByBookingID is a helper method to define mock.On call
//   - bookingID uint64
func (_e *MockReviewDatabase_Expecter) FindByBookingID(bookingID interface{}) *MockReviewDatabase_FindByBookingID_Call {
	return &MockReviewDatabase_FindByBookingID_Call{Call: _e.mock.On("FindByBookingID", bookingID)}
}

func (_c *MockReviewDatabase_FindByBookingID_Call) Run(run func(bookingID uint64)) *MockReviewDatabase_FindByBookingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindByBookingID_Call) Return(review *model.Review, err error) *MockReviewDatabase_FindByBookingID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewDatabase_FindByBookingID_Call) RunAndReturn(run func(bookingID uint64) (*model.Review, error)) *MockReviewDatabase_FindByBookingID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHallID provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindByHallID(hallID uint64) ([]model.Review, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for FindByHallID")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) ([]model.Review, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) []model.Review); ok {
		r0 = returnFunc(hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindByHallID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHallID'
type MockReviewDatabase_FindByHallID_Call struct {
	*mock.Call
}

// FindByHallID is a helper method to define mock.On call
//   - hallID uint64
func (_e *MockReviewDatabase_Expecter) FindByHallID(hallID interface{}) *MockReviewDatabase_FindByHallID_Call {
	return &MockReviewDatabase_FindByHallID_Call{Call: _e.mock.On("FindByHallID", hallID)}
}

func (_c *MockReviewDatabase_FindByHallID_Call) Run(run func(hallID uint64)) *MockReviewDatabase_FindByHallID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindByHallID_Call) Return(reviews []model.Review, err error) *MockReviewDatabase_FindByHallID_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewDatabase_FindByHallID_Call) RunAndReturn(run func(hallID uint64) ([]model.Review, error)) *MockReviewDatabase_FindByHallID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindByID(id uint64) (*model.Review, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Review, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Review); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockReviewDatabase_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockReviewDatabase_Expecter) FindByID(id interface{}) *MockReviewDatabase_FindByID_Call {
	return &MockReviewDatabase_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockReviewDatabase_FindByID_Call) Run(run func(id uint64)) *MockReviewDatabase_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindByID_Call) Return(review *model.Review, err error) *MockReviewDatabase_FindByID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewDatabase_FindByID_Call) RunAndReturn(run func(id uint64) (*model.Review, error)) *MockReviewDatabase_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserIDAndBookingID provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindByUserIDAndBookingID(userID uint64, bookingID uint64) (*model.Review, error) {
	ret := _mock.Called(userID, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserIDAndBookingID")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*model.Review, error)); ok {
		return returnFunc(userID, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *model.Review); ok {
		r0 = returnFunc(userID, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = returnFunc(userID, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindByUserIDAndBookingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserIDAndBookingID'
type MockReviewDatabase_FindByUserIDAndBookingID_Call struct {
	*mock.Call
}

// FindByUserIDAndBookingID is a helper method to define mock.On call
//   - userID uint64
//   - bookingID uint64
func (_e *MockReviewDatabase_Expecter) FindByUserIDAndBookingID(userID interface{}, bookingID interface{}) *MockReviewDatabase_FindByUserIDAndBookingID_Call {
	return &MockReviewDatabase_FindByUserIDAndBookingID_Call{Call: _e.mock.On("FindByUserIDAndBookingID", userID, bookingID)}
}

func (_c *MockReviewDatabase_FindByUserIDAndBookingID_Call) Run(run func(userID uint64, bookingID uint64)) *MockReviewDatabase_FindByUserIDAndBookingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindByUserIDAndBookingID_Call) Return(review *model.Review, err error) *MockReviewDatabase_FindByUserIDAndBookingID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewDatabase_FindByUserIDAndBookingID_Call) RunAndReturn(run func(userID uint64, bookingID uint64) (*model.Review, error)) *MockReviewDatabase_FindByUserIDAndBookingID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) Update(review *model.Review) error {
	ret := _mock.Called(review)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Review) error); ok {
		r0 = returnFunc(review)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockReviewDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - review *model.Review
func (_e *MockReviewDatabase_Expecter) Update(review interface{}) *MockReviewDatabase_Update_Call {
	return &MockReviewDatabase_Update_Call{Call: _e.mock.On("Update", review)}
}

func (_c *MockReviewDatabase_Update_Call) Run(run func(review *model.Review)) *MockReviewDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Review
		if args[0] != nil {
			arg0 = args[0].(*model.Review)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_Update_Call) Return(err error) *MockReviewDatabase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewDatabase_Update_Call) RunAndReturn(run func(review *model.Review) error) *MockReviewDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}
