// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"
	"college-graduation-project-backend/internal/model/request"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserService
func (_mock *MockUserService) Create(user *model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *model.User
func (_e *MockUserService_Expecter) Create(user interface{}) *MockUserService_Create_Call {
	return &MockUserService_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUserService_Create_Call) Run(run func(user *model.User)) *MockUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_Create_Call) Return(err error) *MockUserService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Create_Call) RunAndReturn(run func(user *model.User) error) *MockUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserService
func (_mock *MockUserService) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockUserService_Expecter) Delete(id interface{}) *MockUserService_Delete_Call {
	return &MockUserService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockUserService_Delete_Call) Run(run func(id uint64)) *MockUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_Delete_Call) Return(err error) *MockUserService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Delete_Call) RunAndReturn(run func(id uint64) error) *MockUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockUserService
func (_mock *MockUserService) FindAll() ([]model.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockUserService_Expecter) FindAll() *MockUserService_FindAll_Call {
	return &MockUserService_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockUserService_FindAll_Call) Run(run func()) *MockUserService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserService_FindAll_Call) Return(users []model.User, err error) *MockUserService_FindAll_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserService_FindAll_Call) RunAndReturn(run func() ([]model.User, error)) *MockUserService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) FindByEmail(email string) (*model.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserService_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserService_Expecter) FindByEmail(email interface{}) *MockUserService_FindByEmail_Call {
	return &MockUserService_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *MockUserService_FindByEmail_Call) Run(run func(email string)) *MockUserService_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_FindByEmail_Call) Return(user *model.User, err error) *MockUserService_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_FindByEmail_Call) RunAndReturn(run func(email string) (*model.User, error)) *MockUserService_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserService
func (_mock *MockUserService) FindByID(id uint64) (*model.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockUserService_Expecter) FindByID(id interface{}) *MockUserService_FindByID_Call {
	return &MockUserService_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockUserService_FindByID_Call) Run(run func(id uint64)) *MockUserService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_FindByID_Call) Return(user *model.User, err error) *MockUserService_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_FindByID_Call) RunAndReturn(run func(id uint64) (*model.User, error)) *MockUserService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserService
func (_mock *MockUserService) Update(user *model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *model.User
func (_e *MockUserService_Expecter) Update(user interface{}) *MockUserService_Update_Call {
	return &MockUserService_Update_Call{Call: _e.mock.On("Update", user)}
}

func (_c *MockUserService_Update_Call) Run(run func(user *model.User)) *MockUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_Update_Call) Return(err error) *MockUserService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Update_Call) RunAndReturn(run func(user *model.User) error) *MockUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateProfile(userID uint64, updateProfile request.UpdateProfile) (*model.User, error) {
	ret := _mock.Called(userID, updateProfile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, request.UpdateProfile) (*model.User, error)); ok {
		return returnFunc(userID, updateProfile)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, request.UpdateProfile) *model.User); ok {
		r0 = returnFunc(userID, updateProfile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, request.UpdateProfile) error); ok {
		r1 = returnFunc(userID, updateProfile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - userID uint64
//   - updateProfile request.UpdateProfile
func (_e *MockUserService_Expecter) UpdateProfile(userID interface{}, updateProfile interface{}) *MockUserService_UpdateProfile_Call {
	return &MockUserService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", userID, updateProfile)}
}

func (_c *MockUserService_UpdateProfile_Call) Run(run func(userID uint64, updateProfile request.UpdateProfile)) *MockUserService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 request.UpdateProfile
		if args[1] != nil {
			arg1 = args[1].(request.UpdateProfile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_UpdateProfile_Call) Return(user *model.User, err error) *MockUserService_UpdateProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_UpdateProfile_Call) RunAndReturn(run func(userID uint64, updateProfile request.UpdateProfile) (*model.User, error)) *MockUserService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}
