// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingDatabase creates a new instance of MockBookingDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingDatabase {
	mock := &MockBookingDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingDatabase is an autogenerated mock type for the BookingDatabase type
type MockBookingDatabase struct {
	mock.Mock
}

type MockBookingDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingDatabase) EXPECT() *MockBookingDatabase_Expecter {
	return &MockBookingDatabase_Expecter{mock: &_m.Mock}
}

// CheckConflict provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) CheckConflict(hallID uint64, startDateTime time.Time, endDateTime time.Time) (bool, error) {
	ret := _mock.Called(hallID, startDateTime, endDateTime)

	if len(ret) == 0 {
		panic("no return value specified for CheckConflict")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) (bool, error)); ok {
		return returnFunc(hallID, startDateTime, endDateTime)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) bool); ok {
		r0 = returnFunc(hallID, startDateTime, endDateTime)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time) error); ok {
		r1 = returnFunc(hallID, startDateTime, endDateTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_CheckConflict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckConflict'
type MockBookingDatabase_CheckConflict_Call struct {
	*mock.Call
}

// CheckConflict is a helper method to define mock.On call
//   - hallID uint64
//   - startDateTime time.Time
//   - endDateTime time.Time
func (_e *MockBookingDatabase_Expecter) CheckConflict(hallID interface{}, startDateTime interface{}, endDateTime interface{}) *MockBookingDatabase_CheckConflict_Call {
	return &MockBookingDatabase_CheckConflict_Call{Call: _e.mock.On("CheckConflict", hallID, startDateTime, endDateTime)}
}

func (_c *MockBookingDatabase_CheckConflict_Call) Run(run func(hallID uint64, startDateTime time.Time, endDateTime time.Time)) *MockBookingDatabase_CheckConflict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_CheckConflict_Call) Return(b bool, err error) *MockBookingDatabase_CheckConflict_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBookingDatabase_CheckConflict_Call) RunAndReturn(run func(hallID uint64, startDateTime time.Time, endDateTime time.Time) (bool, error)) *MockBookingDatabase_CheckConflict_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) Create(booking *model.Booking) error {
	ret := _mock.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Booking) error); ok {
		r0 = returnFunc(booking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - booking *model.Booking
func (_e *MockBookingDatabase_Expecter) Create(booking interface{}) *MockBookingDatabase_Create_Call {
	return &MockBookingDatabase_Create_Call{Call: _e.mock.On("Create", booking)}
}

func (_c *MockBookingDatabase_Create_Call) Run(run func(booking *model.Booking)) *MockBookingDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Booking
		if args[0] != nil {
			arg0 = args[0].(*model.Booking)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_Create_Call) Return(err error) *MockBookingDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingDatabase_Create_Call) RunAndReturn(run func(booking *model.Booking) error) *MockBookingDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBookingDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockBookingDatabase_Expecter) Delete(id interface{}) *MockBookingDatabase_Delete_Call {
	return &MockBookingDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockBookingDatabase_Delete_Call) Run(run func(id uint64)) *MockBookingDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_Delete_Call) Return(err error) *MockBookingDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockBookingDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) FindAll(hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time) ([]model.Booking, error) {
	ret := _mock.Called(hallID, bookingUserID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64, *time.Time, *time.Time) ([]model.Booking, error)); ok {
		return returnFunc(hallID, bookingUserID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64, *time.Time, *time.Time) []model.Booking); ok {
		r0 = returnFunc(hallID, bookingUserID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*uint64, *uint64, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(hallID, bookingUserID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBookingDatabase_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - hallID *uint64
//   - bookingUserID *uint64
//   - from *time.Time
//   - to *time.Time
func (_e *MockBookingDatabase_Expecter) FindAll(hallID interface{}, bookingUserID interface{}, from interface{}, to interface{}) *MockBookingDatabase_FindAll_Call {
	return &MockBookingDatabase_FindAll_Call{Call: _e.mock.On("FindAll", hallID, bookingUserID, from, to)}
}

func (_c *MockBookingDatabase_FindAll_Call) Run(run func(hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time)) *MockBookingDatabase_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *uint64
		if args[0] != nil {
			arg0 = args[0].(*uint64)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_FindAll_Call) Return(bookings []model.Booking, err error) *MockBookingDatabase_FindAll_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingDatabase_FindAll_Call) RunAndReturn(run func(hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time) ([]model.Booking, error)) *MockBookingDatabase_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllFromUser provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) FindAllFromUser(userID uint64, from *time.Time, to *time.Time) ([]model.Booking, error) {
	ret := _mock.Called(userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindAllFromUser")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *time.Time, *time.Time) ([]model.Booking, error)); ok {
		return returnFunc(userID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *time.Time, *time.Time) []model.Booking); ok {
		r0 = returnFunc(userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(userID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_FindAllFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllFromUser'
type MockBookingDatabase_FindAllFromUser_Call struct {
	*mock.Call
}

// FindAllFromUser is a helper method to define mock.On call
//   - userID uint64
//   - from *time.Time
//   - to *time.Time
func (_e *MockBookingDatabase_Expecter) FindAllFromUser(userID interface{}, from interface{}, to interface{}) *MockBookingDatabase_FindAllFromUser_Call {
	return &MockBookingDatabase_FindAllFromUser_Call{Call: _e.mock.On("FindAllFromUser", userID, from, to)}
}

func (_c *MockBookingDatabase_FindAllFromUser_Call) Run(run func(userID uint64, from *time.Time, to *time.Time)) *MockBookingDatabase_FindAllFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_FindAllFromUser_Call) Return(bookings []model.Booking, err error) *MockBookingDatabase_FindAllFromUser_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingDatabase_FindAllFromUser_Call) RunAndReturn(run func(userID uint64, from *time.Time, to *time.Time) ([]model.Booking, error)) *MockBookingDatabase_FindAllFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindBookingsForHall provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) FindBookingsForHall(hallID uint64, from time.Time, to time.Time) ([]model.Booking, error) {
	ret := _mock.Called(hallID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindBookingsForHall")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) ([]model.Booking, error)); ok {
		return returnFunc(hallID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) []model.Booking); ok {
		r0 = returnFunc(hallID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time) error); ok {
		r1 = returnFunc(hallID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_FindBookingsForHall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBookingsForHall'
type MockBookingDatabase_FindBookingsForHall_Call struct {
	*mock.Call
}

// FindBookingsForHall is a helper method to define mock.On call
//   - hallID uint64
//   - from time.Time
//   - to time.Time
func (_e *MockBookingDatabase_Expecter) FindBookingsForHall(hallID interface{}, from interface{}, to interface{}) *MockBookingDatabase_FindBookingsForHall_Call {
	return &MockBookingDatabase_FindBookingsForHall_Call{Call: _e.mock.On("FindBookingsForHall", hallID, from, to)}
}

func (_c *MockBookingDatabase_FindBookingsForHall_Call) Run(run func(hallID uint64, from time.Time, to time.Time)) *MockBookingDatabase_FindBookingsForHall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_FindBookingsForHall_Call) Return(bookings []model.Booking, err error) *MockBookingDatabase_FindBookingsForHall_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingDatabase_FindBookingsForHall_Call) RunAndReturn(run func(hallID uint64, from time.Time, to time.Time) ([]model.Booking, error)) *MockBookingDatabase_FindBookingsForHall_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) FindByID(id uint64) (*model.Booking, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Booking, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Booking); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBookingDatabase_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockBookingDatabase_Expecter) FindByID(id interface{}) *MockBookingDatabase_FindByID_Call {
	return &MockBookingDatabase_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockBookingDatabase_FindByID_Call) Run(run func(id uint64)) *MockBookingDatabase_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_FindByID_Call) Return(booking *model.Booking, err error) *MockBookingDatabase_FindByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingDatabase_FindByID_Call) RunAndReturn(run func(id uint64) (*model.Booking, error)) *MockBookingDatabase_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) Update(booking *model.Booking) error {
	ret := _mock.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Booking) error); ok {
		r0 = returnFunc(booking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBookingDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - booking *model.Booking
func (_e *MockBookingDatabase_Expecter) Update(booking interface{}) *MockBookingDatabase_Update_Call {
	return &MockBookingDatabase_Update_Call{Call: _e.mock.On("Update", booking)}
}

func (_c *MockBookingDatabase_Update_Call) Run(run func(booking *model.Booking)) *MockBookingDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Booking
		if args[0] != nil {
			arg0 = args[0].(*model.Booking)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_Update_Call) Return(err error) *MockBookingDatabase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingDatabase_Update_Call) RunAndReturn(run func(booking *model.Booking) error) *MockBookingDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}
