// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"
	"college-graduation-project-backend/internal/model/request"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReviewService creates a new instance of MockReviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewService {
	mock := &MockReviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewService is an autogenerated mock type for the ReviewService type
type MockReviewService struct {
	mock.Mock
}

type MockReviewService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewService) EXPECT() *MockReviewService_Expecter {
	return &MockReviewService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReviewService
func (_mock *MockReviewService) Create(userID uint64, bookingID uint64, req *request.ReviewCreate) (*model.Review, error) {
	ret := _mock.Called(userID, bookingID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.ReviewCreate) (*model.Review, error)); ok {
		return returnFunc(userID, bookingID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.ReviewCreate) *model.Review); ok {
		r0 = returnFunc(userID, bookingID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, *request.ReviewCreate) error); ok {
		r1 = returnFunc(userID, bookingID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReviewService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userID uint64
//   - bookingID uint64
//   - req *request.ReviewCreate
func (_e *MockReviewService_Expecter) Create(userID interface{}, bookingID interface{}, req interface{}) *MockReviewService_Create_Call {
	return &MockReviewService_Create_Call{Call: _e.mock.On("Create", userID, bookingID, req)}
}

func (_c *MockReviewService_Create_Call) Run(run func(userID uint64, bookingID uint64, req *request.ReviewCreate)) *MockReviewService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *request.ReviewCreate
		if args[2] != nil {
			arg2 = args[2].(*request.ReviewCreate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReviewService_Create_Call) Return(review *model.Review, err error) *MockReviewService_Create_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewService_Create_Call) RunAndReturn(run func(userID uint64, bookingID uint64, req *request.ReviewCreate) (*model.Review, error)) *MockReviewService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockReviewService
func (_mock *MockReviewService) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReviewService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockReviewService_Expecter) Delete(id interface{}) *MockReviewService_Delete_Call {
	return &MockReviewService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockReviewService_Delete_Call) Run(run func(id uint64)) *MockReviewService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewService_Delete_Call) Return(err error) *MockReviewService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewService_Delete_Call) RunAndReturn(run func(id uint64) error) *MockReviewService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllWithFilters provides a mock function for the type MockReviewService
func (_mock *MockReviewService) GetAllWithFilters(hallID *uint64, minRating *uint64) ([]model.Review, error) {
	ret := _mock.Called(hallID, minRating)

	if len(ret) == 0 {
		panic("no return value specified for GetAllWithFilters")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) ([]model.Review, error)); ok {
		return returnFunc(hallID, minRating)
	}
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) []model.Review); ok {
		r0 = returnFunc(hallID, minRating)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*uint64, *uint64) error); ok {
		r1 = returnFunc(hallID, minRating)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_GetAllWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllWithFilters'
type MockReviewService_GetAllWithFilters_Call struct {
	*mock.Call
}

// GetAllWithFilters is a helper method to define mock.On call
//   - hallID *uint64
//   - minRating *uint64
func (_e *MockReviewService_Expecter) GetAllWithFilters(hallID interface{}, minRating interface{}) *MockReviewService_GetAllWithFilters_Call {
	return &MockReviewService_GetAllWithFilters_Call{Call: _e.mock.On("GetAllWithFilters", hallID, minRating)}
}

func (_c *MockReviewService_GetAllWithFilters_Call) Run(run func(hallID *uint64, minRating *uint64)) *MockReviewService_GetAllWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *uint64
		if args[0] != nil {
			arg0 = args[0].(*uint64)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewService_GetAllWithFilters_Call) Return(reviews []model.Review, err error) *MockReviewService_GetAllWithFilters_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewService_GetAllWithFilters_Call) RunAndReturn(run func(hallID *uint64, minRating *uint64) ([]model.Review, error)) *MockReviewService_GetAllWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetByBookingID provides a mock function for the type MockReviewService
func (_mock *MockReviewService) GetByBookingID(userID uint64, bookingID uint64) (*model.Review, error) {
	ret := _mock.Called(userID, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for GetByBookingID")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*model.Review, error)); ok {
		return returnFunc(userID, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *model.Review); ok {
		r0 = returnFunc(userID, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = returnFunc(userID, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_GetByBookingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByBookingID'
type MockReviewService_GetByBookingID_Call struct {
	*mock.Call
}

// GetByBookingID is a helper method to define mock.On call
//   - userID uint64
//   - bookingID uint64
func (_e *MockReviewService_Expecter) GetByBookingID(userID interface{}, bookingID interface{}) *MockReviewService_GetByBookingID_Call {
	return &MockReviewService_GetByBookingID_Call{Call: _e.mock.On("GetByBookingID", userID, bookingID)}
}

func (_c *MockReviewService_GetByBookingID_Call) Run(run func(userID uint64, bookingID uint64)) *MockReviewService_GetByBookingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewService_GetByBookingID_Call) Return(review *model.Review, err error) *MockReviewService_GetByBookingID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewService_GetByBookingID_Call) RunAndReturn(run func(userID uint64, bookingID uint64) (*model.Review, error)) *MockReviewService_GetByBookingID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHallID provides a mock function for the type MockReviewService
func (_mock *MockReviewService) GetByHallID(hallID uint64) ([]model.Review, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for GetByHallID")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) ([]model.Review, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) []model.Review); ok {
		r0 = returnFunc(hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_GetByHallID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHallID'
type MockReviewService_GetByHallID_Call struct {
	*mock.Call
}

// GetByHallID is a helper method to define mock.On call
//   - hallID uint64
func (_e *MockReviewService_Expecter) GetByHallID(hallID interface{}) *MockReviewService_GetByHallID_Call {
	return &MockReviewService_GetByHallID_Call{Call: _e.mock.On("GetByHallID", hallID)}
}

func (_c *MockReviewService_GetByHallID_Call) Run(run func(hallID uint64)) *MockReviewService_GetByHallID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewService_GetByHallID_Call) Return(reviews []model.Review, err error) *MockReviewService_GetByHallID_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewService_GetByHallID_Call) RunAndReturn(run func(hallID uint64) ([]model.Review, error)) *MockReviewService_GetByHallID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockReviewService
func (_mock *MockReviewService) Update(userID uint64, reviewID uint64, req *request.ReviewCreate) (*model.Review, error) {
	ret := _mock.Called(userID, reviewID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.ReviewCreate) (*model.Review, error)); ok {
		return returnFunc(userID, reviewID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.ReviewCreate) *model.Review); ok {
		r0 = returnFunc(userID, reviewID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, *request.ReviewCreate) error); ok {
		r1 = returnFunc(userID, reviewID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockReviewService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID uint64
//   - reviewID uint64
//   - req *request.ReviewCreate
func (_e *MockReviewService_Expecter) Update(userID interface{}, reviewID interface{}, req interface{}) *MockReviewService_Update_Call {
	return &MockReviewService_Update_Call{Call: _e.mock.On("Update", userID, reviewID, req)}
}

func (_c *MockReviewService_Update_Call) Run(run func(userID uint64, reviewID uint64, req *request.ReviewCreate)) *MockReviewService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *request.ReviewCreate
		if args[2] != nil {
			arg2 = args[2].(*request.ReviewCreate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReviewService_Update_Call) Return(review *model.Review, err error) *MockReviewService_Update_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewService_Update_Call) RunAndReturn(run func(userID uint64, reviewID uint64, req *request.ReviewCreate) (*model.Review, error)) *MockReviewService_Update_Call {
	_c.Call.Return(run)
	return _c
}
