// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserAgreementDatabase creates a new instance of MockUserAgreementDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAgreementDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAgreementDatabase {
	mock := &MockUserAgreementDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAgreementDatabase is an autogenerated mock type for the UserAgreementDatabase type
type MockUserAgreementDatabase struct {
	mock.Mock
}

type MockUserAgreementDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAgreementDatabase) EXPECT() *MockUserAgreementDatabase_Expecter {
	return &MockUserAgreementDatabase_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockUserAgreementDatabase
func (_mock *MockUserAgreementDatabase) Get() (*model.UserAgreement, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.UserAgreement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.UserAgreement, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.UserAgreement); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAgreement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAgreementDatabase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserAgreementDatabase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockUserAgreementDatabase_Expecter) Get() *MockUserAgreementDatabase_Get_Call {
	return &MockUserAgreementDatabase_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockUserAgreementDatabase_Get_Call) Run(run func()) *MockUserAgreementDatabase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserAgreementDatabase_Get_Call) Return(userAgreement *model.UserAgreement, err error) *MockUserAgreementDatabase_Get_Call {
	_c.Call.Return(userAgreement, err)
	return _c
}

func (_c *MockUserAgreementDatabase_Get_Call) RunAndReturn(run func() (*model.UserAgreement, error)) *MockUserAgreementDatabase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserAgreementDatabase
func (_mock *MockUserAgreementDatabase) Save(text string) (*model.UserAgreement, error) {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.UserAgreement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.UserAgreement, error)); ok {
		return returnFunc(text)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.UserAgreement); ok {
		r0 = returnFunc(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAgreement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAgreementDatabase_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserAgreementDatabase_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - text string
func (_e *MockUserAgreementDatabase_Expecter) Save(text interface{}) *MockUserAgreementDatabase_Save_Call {
	return &MockUserAgreementDatabase_Save_Call{Call: _e.mock.On("Save", text)}
}

func (_c *MockUserAgreementDatabase_Save_Call) Run(run func(text string)) *MockUserAgreementDatabase_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserAgreementDatabase_Save_Call) Return(userAgreement *model.UserAgreement, err error) *MockUserAgreementDatabase_Save_Call {
	_c.Call.Return(userAgreement, err)
	return _c
}

func (_c *MockUserAgreementDatabase_Save_Call) RunAndReturn(run func(text string) (*model.UserAgreement, error)) *MockUserAgreementDatabase_Save_Call {
	_c.Call.Return(run)
	return _c
}
