// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReportDatabase creates a new instance of MockReportDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportDatabase {
	mock := &MockReportDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportDatabase is an autogenerated mock type for the ReportDatabase type
type MockReportDatabase struct {
	mock.Mock
}

type MockReportDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportDatabase) EXPECT() *MockReportDatabase_Expecter {
	return &MockReportDatabase_Expecter{mock: &_m.Mock}
}

// CountHalls provides a mock function for the type MockReportDatabase
func (_mock *MockReportDatabase) CountHalls(hallID *uint64) (uint64, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for CountHalls")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*uint64) (uint64, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(*uint64) uint64); ok {
		r0 = returnFunc(hallID)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(*uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDatabase_CountHalls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountHalls'
type MockReportDatabase_CountHalls_Call struct {
	*mock.Call
}

// CountHalls is a helper method to define mock.On call
//   - hallID *uint64
func (_e *MockReportDatabase_Expecter) CountHalls(hallID interface{}) *MockReportDatabase_CountHalls_Call {
	return &MockReportDatabase_CountHalls_Call{Call: _e.mock.On("CountHalls", hallID)}
}

func (_c *MockReportDatabase_CountHalls_Call) Run(run func(hallID *uint64)) *MockReportDatabase_CountHalls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *uint64
		if args[0] != nil {
			arg0 = args[0].(*uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReportDatabase_CountHalls_Call) Return(v uint64, err error) *MockReportDatabase_CountHalls_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockReportDatabase_CountHalls_Call) RunAndReturn(run func(hallID *uint64) (uint64, error)) *MockReportDatabase_CountHalls_Call {
	_c.Call.Return(run)
	return _c
}

// FindReportBookings provides a mock function for the type MockReportDatabase
func (_mock *MockReportDatabase) FindReportBookings(from time.Time, to time.Time, hallID *uint64) ([]model.Booking, error) {
	ret := _mock.Called(from, to, hallID)

	if len(ret) == 0 {
		panic("no return value specified for FindReportBookings")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time, *uint64) ([]model.Booking, error)); ok {
		return returnFunc(from, to, hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time, *uint64) []model.Booking); ok {
		r0 = returnFunc(from, to, hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time, time.Time, *uint64) error); ok {
		r1 = returnFunc(from, to, hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDatabase_FindReportBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindReportBookings'
type MockReportDatabase_FindReportBookings_Call struct {
	*mock.Call
}

// FindReportBookings is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
func (_e *MockReportDatabase_Expecter) FindReportBookings(from interface{}, to interface{}, hallID interface{}) *MockReportDatabase_FindReportBookings_Call {
	return &MockReportDatabase_FindReportBookings_Call{Call: _e.mock.On("FindReportBookings", from, to, hallID)}
}

func (_c *MockReportDatabase_FindReportBookings_Call) Run(run func(from time.Time, to time.Time, hallID *uint64)) *MockReportDatabase_FindReportBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *uint64
		if args[2] != nil {
			arg2 = args[2].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReportDatabase_FindReportBookings_Call) Return(bookings []model.Booking, err error) *MockReportDatabase_FindReportBookings_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockReportDatabase_FindReportBookings_Call) RunAndReturn(run func(from time.Time, to time.Time, hallID *uint64) ([]model.Booking, error)) *MockReportDatabase_FindReportBookings_Call {
	_c.Call.Return(run)
	return _c
}

// FindSalesBookings provides a mock function for the type MockReportDatabase
func (_mock *MockReportDatabase) FindSalesBookings(from time.Time, to time.Time, hallID *uint64) ([]model.Booking, error) {
	ret := _mock.Called(from, to, hallID)

	if len(ret) == 0 {
		panic("no return value specified for FindSalesBookings")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time, *uint64) ([]model.Booking, error)); ok {
		return returnFunc(from, to, hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time, *uint64) []model.Booking); ok {
		r0 = returnFunc(from, to, hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time, time.Time, *uint64) error); ok {
		r1 = returnFunc(from, to, hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDatabase_FindSalesBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSalesBookings'
type MockReportDatabase_FindSalesBookings_Call struct {
	*mock.Call
}

// FindSalesBookings is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
func (_e *MockReportDatabase_Expecter) FindSalesBookings(from interface{}, to interface{}, hallID interface{}) *MockReportDatabase_FindSalesBookings_Call {
	return &MockReportDatabase_FindSalesBookings_Call{Call: _e.mock.On("FindSalesBookings", from, to, hallID)}
}

func (_c *MockReportDatabase_FindSalesBookings_Call) Run(run func(from time.Time, to time.Time, hallID *uint64)) *MockReportDatabase_FindSalesBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *uint64
		if args[2] != nil {
			arg2 = args[2].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReportDatabase_FindSalesBookings_Call) Return(bookings []model.Booking, err error) *MockReportDatabase_FindSalesBookings_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockReportDatabase_FindSalesBookings_Call) RunAndReturn(run func(from time.Time, to time.Time, hallID *uint64) ([]model.Booking, error)) *MockReportDatabase_FindSalesBookings_Call {
	_c.Call.Return(run)
	return _c
}
