// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model/response"

	mock "github.com/stretchr/testify/mock"
)

// NewMockImageService creates a new instance of MockImageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageService {
	mock := &MockImageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageService is an autogenerated mock type for the ImageService type
type MockImageService struct {
	mock.Mock
}

type MockImageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageService) EXPECT() *MockImageService_Expecter {
	return &MockImageService_Expecter{mock: &_m.Mock}
}

// DeleteHallImage provides a mock function for the type MockImageService
func (_mock *MockImageService) DeleteHallImage(userID uint64, hallID uint64, imageID uint64) error {
	ret := _mock.Called(userID, hallID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHallImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, uint64) error); ok {
		r0 = returnFunc(userID, hallID, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_DeleteHallImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHallImage'
type MockImageService_DeleteHallImage_Call struct {
	*mock.Call
}

// DeleteHallImage is a helper method to define mock.On call
//   - userID uint64
//   - hallID uint64
//   - imageID uint64
func (_e *MockImageService_Expecter) DeleteHallImage(userID interface{}, hallID interface{}, imageID interface{}) *MockImageService_DeleteHallImage_Call {
	return &MockImageService_DeleteHallImage_Call{Call: _e.mock.On("DeleteHallImage", userID, hallID, imageID)}
}

func (_c *MockImageService_DeleteHallImage_Call) Run(run func(userID uint64, hallID uint64, imageID uint64)) *MockImageService_DeleteHallImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageService_DeleteHallImage_Call) Return(err error) *MockImageService_DeleteHallImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_DeleteHallImage_Call) RunAndReturn(run func(userID uint64, hallID uint64, imageID uint64) error) *MockImageService_DeleteHallImage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserAvatar provides a mock function for the type MockImageService
func (_mock *MockImageService) DeleteUserAvatar(userID uint64) error {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserAvatar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_DeleteUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserAvatar'
type MockImageService_DeleteUserAvatar_Call struct {
	*mock.Call
}

// DeleteUserAvatar is a helper method to define mock.On call
//   - userID uint64
func (_e *MockImageService_Expecter) DeleteUserAvatar(userID interface{}) *MockImageService_DeleteUserAvatar_Call {
	return &MockImageService_DeleteUserAvatar_Call{Call: _e.mock.On("DeleteUserAvatar", userID)}
}

func (_c *MockImageService_DeleteUserAvatar_Call) Run(run func(userID uint64)) *MockImageService_DeleteUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_DeleteUserAvatar_Call) Return(err error) *MockImageService_DeleteUserAvatar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_DeleteUserAvatar_Call) RunAndReturn(run func(userID uint64) error) *MockImageService_DeleteUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetHallImages provides a mock function for the type MockImageService
func (_mock *MockImageService) GetHallImages(hallID uint64) ([]string, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for GetHallImages")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) ([]string, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) []string); ok {
		r0 = returnFunc(hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetHallImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHallImages'
type MockImageService_GetHallImages_Call struct {
	*mock.Call
}

// GetHallImages is a helper method to define mock.On call
//   - hallID uint64
func (_e *MockImageService_Expecter) GetHallImages(hallID interface{}) *MockImageService_GetHallImages_Call {
	return &MockImageService_GetHallImages_Call{Call: _e.mock.On("GetHallImages", hallID)}
}

func (_c *MockImageService_GetHallImages_Call) Run(run func(hallID uint64)) *MockImageService_GetHallImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_GetHallImages_Call) Return(strings []string, err error) *MockImageService_GetHallImages_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockImageService_GetHallImages_Call) RunAndReturn(run func(hallID uint64) ([]string, error)) *MockImageService_GetHallImages_Call {
	_c.Call.Return(run)
	return _c
}

// GetHallImagesWithIDs provides a mock function for the type MockImageService
func (_mock *MockImageService) GetHallImagesWithIDs(hallID uint64) ([]response.HallImageWithID, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for GetHallImagesWithIDs")
	}

	var r0 []response.HallImageWithID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) ([]response.HallImageWithID, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) []response.HallImageWithID); ok {
		r0 = returnFunc(hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.HallImageWithID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetHallImagesWithIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHallImagesWithIDs'
type MockImageService_GetHallImagesWithIDs_Call struct {
	*mock.Call
}

// GetHallImagesWithIDs is a helper method to define mock.On call
//   - hallID uint64
func (_e *MockImageService_Expecter) GetHallImagesWithIDs(hallID interface{}) *MockImageService_GetHallImagesWithIDs_Call {
	return &MockImageService_GetHallImagesWithIDs_Call{Call: _e.mock.On("GetHallImagesWithIDs", hallID)}
}

func (_c *MockImageService_GetHallImagesWithIDs_Call) Run(run func(hallID uint64)) *MockImageService_GetHallImagesWithIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_GetHallImagesWithIDs_Call) Return(hallImageWithIDs []response.HallImageWithID, err error) *MockImageService_GetHallImagesWithIDs_Call {
	_c.Call.Return(hallImageWithIDs, err)
	return _c
}

func (_c *MockImageService_GetHallImagesWithIDs_Call) RunAndReturn(run func(hallID uint64) ([]response.HallImageWithID, error)) *MockImageService_GetHallImagesWithIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAvatar provides a mock function for the type MockImageService
func (_mock *MockImageService) GetUserAvatar(userID uint64) (*string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAvatar")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *string); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAvatar'
type MockImageService_GetUserAvatar_Call struct {
	*mock.Call
}

// GetUserAvatar is a helper method to define mock.On call
//   - userID uint64
func (_e *MockImageService_Expecter) GetUserAvatar(userID interface{}) *MockImageService_GetUserAvatar_Call {
	return &MockImageService_GetUserAvatar_Call{Call: _e.mock.On("GetUserAvatar", userID)}
}

func (_c *MockImageService_GetUserAvatar_Call) Run(run func(userID uint64)) *MockImageService_GetUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_GetUserAvatar_Call) Return(s *string, err error) *MockImageService_GetUserAvatar_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockImageService_GetUserAvatar_Call) RunAndReturn(run func(userID uint64) (*string, error)) *MockImageService_GetUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserAvatar provides a mock function for the type MockImageService
func (_mock *MockImageService) SetUserAvatar(userID uint64, imagePath string) error {
	ret := _mock.Called(userID, imagePath)

	if len(ret) == 0 {
		panic("no return value specified for SetUserAvatar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, string) error); ok {
		r0 = returnFunc(userID, imagePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_SetUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserAvatar'
type MockImageService_SetUserAvatar_Call struct {
	*mock.Call
}

// SetUserAvatar is a helper method to define mock.On call
//   - userID uint64
//   - imagePath string
func (_e *MockImageService_Expecter) SetUserAvatar(userID interface{}, imagePath interface{}) *MockImageService_SetUserAvatar_Call {
	return &MockImageService_SetUserAvatar_Call{Call: _e.mock.On("SetUserAvatar", userID, imagePath)}
}

func (_c *MockImageService_SetUserAvatar_Call) Run(run func(userID uint64, imagePath string)) *MockImageService_SetUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageService_SetUserAvatar_Call) Return(err error) *MockImageService_SetUserAvatar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_SetUserAvatar_Call) RunAndReturn(run func(userID uint64, imagePath string) error) *MockImageService_SetUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// UploadHallImage provides a mock function for the type MockImageService
func (_mock *MockImageService) UploadHallImage(userID uint64, hallID uint64, imagePath string) error {
	ret := _mock.Called(userID, hallID, imagePath)

	if len(ret) == 0 {
		panic("no return value specified for UploadHallImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, string) error); ok {
		r0 = returnFunc(userID, hallID, imagePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_UploadHallImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadHallImage'
type MockImageService_UploadHallImage_Call struct {
	*mock.Call
}

// UploadHallImage is a helper method to define mock.On call
//   - userID uint64
//   - hallID uint64
//   - imagePath string
func (_e *MockImageService_Expecter) UploadHallImage(userID interface{}, hallID interface{}, imagePath interface{}) *MockImageService_UploadHallImage_Call {
	return &MockImageService_UploadHallImage_Call{Call: _e.mock.On("UploadHallImage", userID, hallID, imagePath)}
}

func (_c *MockImageService_UploadHallImage_Call) Run(run func(userID uint64, hallID uint64, imagePath string)) *MockImageService_UploadHallImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageService_UploadHallImage_Call) Return(err error) *MockImageService_UploadHallImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_UploadHallImage_Call) RunAndReturn(run func(userID uint64, hallID uint64, imagePath string) error) *MockImageService_UploadHallImage_Call {
	_c.Call.Return(run)
	return _c
}
