// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"
	"college-graduation-project-backend/internal/model/request"
	"college-graduation-project-backend/internal/model/response"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHallService creates a new instance of MockHallService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHallService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHallService {
	mock := &MockHallService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHallService is an autogenerated mock type for the HallService type
type MockHallService struct {
	mock.Mock
}

type MockHallService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHallService) EXPECT() *MockHallService_Expecter {
	return &MockHallService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockHallService
func (_mock *MockHallService) Create(userID uint64, hallCreate *request.HallCreate) (*model.Hall, error) {
	ret := _mock.Called(userID, hallCreate)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *request.HallCreate) (*model.Hall, error)); ok {
		return returnFunc(userID, hallCreate)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *request.HallCreate) *model.Hall); ok {
		r0 = returnFunc(userID, hallCreate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *request.HallCreate) error); ok {
		r1 = returnFunc(userID, hallCreate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHallService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userID uint64
//   - hallCreate *request.HallCreate
func (_e *MockHallService_Expecter) Create(userID interface{}, hallCreate interface{}) *MockHallService_Create_Call {
	return &MockHallService_Create_Call{Call: _e.mock.On("Create", userID, hallCreate)}
}

func (_c *MockHallService_Create_Call) Run(run func(userID uint64, hallCreate *request.HallCreate)) *MockHallService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *request.HallCreate
		if args[1] != nil {
			arg1 = args[1].(*request.HallCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHallService_Create_Call) Return(hall *model.Hall, err error) *MockHallService_Create_Call {
	_c.Call.Return(hall, err)
	return _c
}

func (_c *MockHallService_Create_Call) RunAndReturn(run func(userID uint64, hallCreate *request.HallCreate) (*model.Hall, error)) *MockHallService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockHallService
func (_mock *MockHallService) Delete(userID uint64, id uint64) error {
	ret := _mock.Called(userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = returnFunc(userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHallService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHallService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
func (_e *MockHallService_Expecter) Delete(userID interface{}, id interface{}) *MockHallService_Delete_Call {
	return &MockHallService_Delete_Call{Call: _e.mock.On("Delete", userID, id)}
}

func (_c *MockHallService_Delete_Call) Run(run func(userID uint64, id uint64)) *MockHallService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHallService_Delete_Call) Return(err error) *MockHallService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHallService_Delete_Call) RunAndReturn(run func(userID uint64, id uint64) error) *MockHallService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockHallService
func (_mock *MockHallService) FindAll() ([]model.Hall, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Hall, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Hall); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockHallService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockHallService_Expecter) FindAll() *MockHallService_FindAll_Call {
	return &MockHallService_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockHallService_FindAll_Call) Run(run func()) *MockHallService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHallService_FindAll_Call) Return(halls []model.Hall, err error) *MockHallService_FindAll_Call {
	_c.Call.Return(halls, err)
	return _c
}

func (_c *MockHallService_FindAll_Call) RunAndReturn(run func() ([]model.Hall, error)) *MockHallService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllActive provides a mock function for the type MockHallService
func (_mock *MockHallService) FindAllActive() ([]model.Hall, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllActive")
	}

	var r0 []model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Hall, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Hall); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_FindAllActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllActive'
type MockHallService_FindAllActive_Call struct {
	*mock.Call
}

// FindAllActive is a helper method to define mock.On call
func (_e *MockHallService_Expecter) FindAllActive() *MockHallService_FindAllActive_Call {
	return &MockHallService_FindAllActive_Call{Call: _e.mock.On("FindAllActive")}
}

func (_c *MockHallService_FindAllActive_Call) Run(run func()) *MockHallService_FindAllActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHallService_FindAllActive_Call) Return(halls []model.Hall, err error) *MockHallService_FindAllActive_Call {
	_c.Call.Return(halls, err)
	return _c
}

func (_c *MockHallService_FindAllActive_Call) RunAndReturn(run func() ([]model.Hall, error)) *MockHallService_FindAllActive_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockHallService
func (_mock *MockHallService) FindByID(id uint64) (*model.Hall, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Hall, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Hall); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHallService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockHallService_Expecter) FindByID(id interface{}) *MockHallService_FindByID_Call {
	return &MockHallService_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockHallService_FindByID_Call) Run(run func(id uint64)) *MockHallService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallService_FindByID_Call) Return(hall *model.Hall, err error) *MockHallService_FindByID_Call {
	_c.Call.Return(hall, err)
	return _c
}

func (_c *MockHallService_FindByID_Call) RunAndReturn(run func(id uint64) (*model.Hall, error)) *MockHallService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailability provides a mock function for the type MockHallService
func (_mock *MockHallService) GetAvailability(hallID uint64, from time.Time, to time.Time) ([]response.HallAvailability, error) {
	ret := _mock.Called(hallID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailability")
	}

	var r0 []response.HallAvailability
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) ([]response.HallAvailability, error)); ok {
		return returnFunc(hallID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) []response.HallAvailability); ok {
		r0 = returnFunc(hallID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.HallAvailability)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time) error); ok {
		r1 = returnFunc(hallID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_GetAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailability'
type MockHallService_GetAvailability_Call struct {
	*mock.Call
}

// GetAvailability is a helper method to define mock.On call
//   - hallID uint64
//   - from time.Time
//   - to time.Time
func (_e *MockHallService_Expecter) GetAvailability(hallID interface{}, from interface{}, to interface{}) *MockHallService_GetAvailability_Call {
	return &MockHallService_GetAvailability_Call{Call: _e.mock.On("GetAvailability", hallID, from, to)}
}

func (_c *MockHallService_GetAvailability_Call) Run(run func(hallID uint64, from time.Time, to time.Time)) *MockHallService_GetAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHallService_GetAvailability_Call) Return(hallAvailabilitys []response.HallAvailability, err error) *MockHallService_GetAvailability_Call {
	_c.Call.Return(hallAvailabilitys, err)
	return _c
}

func (_c *MockHallService_GetAvailability_Call) RunAndReturn(run func(hallID uint64, from time.Time, to time.Time) ([]response.HallAvailability, error)) *MockHallService_GetAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockHallService
func (_mock *MockHallService) Update(userID uint64, id uint64, hallUpdate *request.HallUpdate) (*model.Hall, error) {
	ret := _mock.Called(userID, id, hallUpdate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.HallUpdate) (*model.Hall, error)); ok {
		return returnFunc(userID, id, hallUpdate)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.HallUpdate) *model.Hall); ok {
		r0 = returnFunc(userID, id, hallUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, *request.HallUpdate) error); ok {
		r1 = returnFunc(userID, id, hallUpdate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHallService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
//   - hallUpdate *request.HallUpdate
func (_e *MockHallService_Expecter) Update(userID interface{}, id interface{}, hallUpdate interface{}) *MockHallService_Update_Call {
	return &MockHallService_Update_Call{Call: _e.mock.On("Update", userID, id, hallUpdate)}
}

func (_c *MockHallService_Update_Call) Run(run func(userID uint64, id uint64, hallUpdate *request.HallUpdate)) *MockHallService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *request.HallUpdate
		if args[2] != nil {
			arg2 = args[2].(*request.HallUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHallService_Update_Call) Return(hall *model.Hall, err error) *MockHallService_Update_Call {
	_c.Call.Return(hall, err)
	return _c
}

func (_c *MockHallService_Update_Call) RunAndReturn(run func(userID uint64, id uint64, hallUpdate *request.HallUpdate) (*model.Hall, error)) *MockHallService_Update_Call {
	_c.Call.Return(run)
	return _c
}
