// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHallDatabase creates a new instance of MockHallDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHallDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHallDatabase {
	mock := &MockHallDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHallDatabase is an autogenerated mock type for the HallDatabase type
type MockHallDatabase struct {
	mock.Mock
}

type MockHallDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHallDatabase) EXPECT() *MockHallDatabase_Expecter {
	return &MockHallDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) Create(hall *model.Hall) error {
	ret := _mock.Called(hall)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Hall) error); ok {
		r0 = returnFunc(hall)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHallDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHallDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - hall *model.Hall
func (_e *MockHallDatabase_Expecter) Create(hall interface{}) *MockHallDatabase_Create_Call {
	return &MockHallDatabase_Create_Call{Call: _e.mock.On("Create", hall)}
}

func (_c *MockHallDatabase_Create_Call) Run(run func(hall *model.Hall)) *MockHallDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Hall
		if args[0] != nil {
			arg0 = args[0].(*model.Hall)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallDatabase_Create_Call) Return(err error) *MockHallDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHallDatabase_Create_Call) RunAndReturn(run func(hall *model.Hall) error) *MockHallDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHallDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHallDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockHallDatabase_Expecter) Delete(id interface{}) *MockHallDatabase_Delete_Call {
	return &MockHallDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockHallDatabase_Delete_Call) Run(run func(id uint64)) *MockHallDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallDatabase_Delete_Call) Return(err error) *MockHallDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHallDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockHallDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) FindAll() ([]model.Hall, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Hall, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Hall); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallDatabase_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockHallDatabase_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockHallDatabase_Expecter) FindAll() *MockHallDatabase_FindAll_Call {
	return &MockHallDatabase_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockHallDatabase_FindAll_Call) Run(run func()) *MockHallDatabase_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHallDatabase_FindAll_Call) Return(halls []model.Hall, err error) *MockHallDatabase_FindAll_Call {
	_c.Call.Return(halls, err)
	return _c
}

func (_c *MockHallDatabase_FindAll_Call) RunAndReturn(run func() ([]model.Hall, error)) *MockHallDatabase_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllActive provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) FindAllActive() ([]model.Hall, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllActive")
	}

	var r0 []model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Hall, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Hall); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallDatabase_FindAllActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllActive'
type MockHallDatabase_FindAllActive_Call struct {
	*mock.Call
}

// FindAllActive is a helper method to define mock.On call
func (_e *MockHallDatabase_Expecter) FindAllActive() *MockHallDatabase_FindAllActive_Call {
	return &MockHallDatabase_FindAllActive_Call{Call: _e.mock.On("FindAllActive")}
}

func (_c *MockHallDatabase_FindAllActive_Call) Run(run func()) *MockHallDatabase_FindAllActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHallDatabase_FindAllActive_Call) Return(halls []model.Hall, err error) *MockHallDatabase_FindAllActive_Call {
	_c.Call.Return(halls, err)
	return _c
}

func (_c *MockHallDatabase_FindAllActive_Call) RunAndReturn(run func() ([]model.Hall, error)) *MockHallDatabase_FindAllActive_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) FindByID(id uint64) (*model.Hall, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Hall, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Hall); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallDatabase_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHallDatabase_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockHallDatabase_Expecter) FindByID(id interface{}) *MockHallDatabase_FindByID_Call {
	return &MockHallDatabase_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockHallDatabase_FindByID_Call) Run(run func(id uint64)) *MockHallDatabase_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallDatabase_FindByID_Call) Return(hall *model.Hall, err error) *MockHallDatabase_FindByID_Call {
	_c.Call.Return(hall, err)
	return _c
}

func (_c *MockHallDatabase_FindByID_Call) RunAndReturn(run func(id uint64) (*model.Hall, error)) *MockHallDatabase_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) Update(hall *model.Hall) error {
	ret := _mock.Called(hall)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Hall) error); ok {
		r0 = returnFunc(hall)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHallDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHallDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - hall *model.Hall
func (_e *MockHallDatabase_Expecter) Update(hall interface{}) *MockHallDatabase_Update_Call {
	return &MockHallDatabase_Update_Call{Call: _e.mock.On("Update", hall)}
}

func (_c *MockHallDatabase_Update_Call) Run(run func(hall *model.Hall)) *MockHallDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Hall
		if args[0] != nil {
			arg0 = args[0].(*model.Hall)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallDatabase_Update_Call) Return(err error) *MockHallDatabase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHallDatabase_Update_Call) RunAndReturn(run func(hall *model.Hall) error) *MockHallDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}
