// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserAgreementService creates a new instance of MockUserAgreementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAgreementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAgreementService {
	mock := &MockUserAgreementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAgreementService is an autogenerated mock type for the UserAgreementService type
type MockUserAgreementService struct {
	mock.Mock
}

type MockUserAgreementService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAgreementService) EXPECT() *MockUserAgreementService_Expecter {
	return &MockUserAgreementService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockUserAgreementService
func (_mock *MockUserAgreementService) Get() (*model.UserAgreement, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.UserAgreement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.UserAgreement, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.UserAgreement); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAgreement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAgreementService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserAgreementService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockUserAgreementService_Expecter) Get() *MockUserAgreementService_Get_Call {
	return &MockUserAgreementService_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockUserAgreementService_Get_Call) Run(run func()) *MockUserAgreementService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserAgreementService_Get_Call) Return(userAgreement *model.UserAgreement, err error) *MockUserAgreementService_Get_Call {
	_c.Call.Return(userAgreement, err)
	return _c
}

func (_c *MockUserAgreementService_Get_Call) RunAndReturn(run func() (*model.UserAgreement, error)) *MockUserAgreementService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserAgreementService
func (_mock *MockUserAgreementService) Update(userID uint64, text string) (*model.UserAgreement, error) {
	ret := _mock.Called(userID, text)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.UserAgreement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, string) (*model.UserAgreement, error)); ok {
		return returnFunc(userID, text)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, string) *model.UserAgreement); ok {
		r0 = returnFunc(userID, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAgreement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, string) error); ok {
		r1 = returnFunc(userID, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAgreementService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserAgreementService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID uint64
//   - text string
func (_e *MockUserAgreementService_Expecter) Update(userID interface{}, text interface{}) *MockUserAgreementService_Update_Call {
	return &MockUserAgreementService_Update_Call{Call: _e.mock.On("Update", userID, text)}
}

func (_c *MockUserAgreementService_Update_Call) Run(run func(userID uint64, text string)) *MockUserAgreementService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAgreementService_Update_Call) Return(userAgreement *model.UserAgreement, err error) *MockUserAgreementService_Update_Call {
	_c.Call.Return(userAgreement, err)
	return _c
}

func (_c *MockUserAgreementService_Update_Call) RunAndReturn(run func(userID uint64, text string) (*model.UserAgreement, error)) *MockUserAgreementService_Update_Call {
	_c.Call.Return(run)
	return _c
}
