// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserDatabase creates a new instance of MockUserDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserDatabase {
	mock := &MockUserDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserDatabase is an autogenerated mock type for the UserDatabase type
type MockUserDatabase struct {
	mock.Mock
}

type MockUserDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserDatabase) EXPECT() *MockUserDatabase_Expecter {
	return &MockUserDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) Create(user *model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *model.User
func (_e *MockUserDatabase_Expecter) Create(user interface{}) *MockUserDatabase_Create_Call {
	return &MockUserDatabase_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUserDatabase_Create_Call) Run(run func(user *model.User)) *MockUserDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_Create_Call) Return(err error) *MockUserDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserDatabase_Create_Call) RunAndReturn(run func(user *model.User) error) *MockUserDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockUserDatabase_Expecter) Delete(id interface{}) *MockUserDatabase_Delete_Call {
	return &MockUserDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockUserDatabase_Delete_Call) Run(run func(id uint64)) *MockUserDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_Delete_Call) Return(err error) *MockUserDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockUserDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) FindAll() ([]model.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDatabase_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserDatabase_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockUserDatabase_Expecter) FindAll() *MockUserDatabase_FindAll_Call {
	return &MockUserDatabase_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockUserDatabase_FindAll_Call) Run(run func()) *MockUserDatabase_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserDatabase_FindAll_Call) Return(users []model.User, err error) *MockUserDatabase_FindAll_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserDatabase_FindAll_Call) RunAndReturn(run func() ([]model.User, error)) *MockUserDatabase_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) FindByEmail(email string) (*model.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDatabase_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserDatabase_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserDatabase_Expecter) FindByEmail(email interface{}) *MockUserDatabase_FindByEmail_Call {
	return &MockUserDatabase_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *MockUserDatabase_FindByEmail_Call) Run(run func(email string)) *MockUserDatabase_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_FindByEmail_Call) Return(user *model.User, err error) *MockUserDatabase_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserDatabase_FindByEmail_Call) RunAndReturn(run func(email string) (*model.User, error)) *MockUserDatabase_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) FindByID(id uint64) (*model.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDatabase_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserDatabase_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockUserDatabase_Expecter) FindByID(id interface{}) *MockUserDatabase_FindByID_Call {
	return &MockUserDatabase_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockUserDatabase_FindByID_Call) Run(run func(id uint64)) *MockUserDatabase_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_FindByID_Call) Return(user *model.User, err error) *MockUserDatabase_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserDatabase_FindByID_Call) RunAndReturn(run func(id uint64) (*model.User, error)) *MockUserDatabase_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) Update(user *model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *model.User
func (_e *MockUserDatabase_Expecter) Update(user interface{}) *MockUserDatabase_Update_Call {
	return &MockUserDatabase_Update_Call{Call: _e.mock.On("Update", user)}
}

func (_c *MockUserDatabase_Update_Call) Run(run func(user *model.User)) *MockUserDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_Update_Call) Return(err error) *MockUserDatabase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserDatabase_Update_Call) RunAndReturn(run func(user *model.User) error) *MockUserDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}
