// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"college-graduation-project-backend/internal/model/response"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReportService creates a new instance of MockReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportService {
	mock := &MockReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportService is an autogenerated mock type for the ReportService type
type MockReportService struct {
	mock.Mock
}

type MockReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportService) EXPECT() *MockReportService_Expecter {
	return &MockReportService_Expecter{mock: &_m.Mock}
}

// GetBookingsDynamicsReport provides a mock function for the type MockReportService
func (_mock *MockReportService) GetBookingsDynamicsReport(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string) (*response.BookingsDynamicsReport, error) {
	ret := _mock.Called(userID, from, to, hallID, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsDynamicsReport")
	}

	var r0 *response.BookingsDynamicsReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string) (*response.BookingsDynamicsReport, error)); ok {
		return returnFunc(userID, from, to, hallID, groupBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string) *response.BookingsDynamicsReport); ok {
		r0 = returnFunc(userID, from, to, hallID, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.BookingsDynamicsReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, string) error); ok {
		r1 = returnFunc(userID, from, to, hallID, groupBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetBookingsDynamicsReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsDynamicsReport'
type MockReportService_GetBookingsDynamicsReport_Call struct {
	*mock.Call
}

// GetBookingsDynamicsReport is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - groupBy string
func (_e *MockReportService_Expecter) GetBookingsDynamicsReport(userID interface{}, from interface{}, to interface{}, hallID interface{}, groupBy interface{}) *MockReportService_GetBookingsDynamicsReport_Call {
	return &MockReportService_GetBookingsDynamicsReport_Call{Call: _e.mock.On("GetBookingsDynamicsReport", userID, from, to, hallID, groupBy)}
}

func (_c *MockReportService_GetBookingsDynamicsReport_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string)) *MockReportService_GetBookingsDynamicsReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReportService_GetBookingsDynamicsReport_Call) Return(bookingsDynamicsReport *response.BookingsDynamicsReport, err error) *MockReportService_GetBookingsDynamicsReport_Call {
	_c.Call.Return(bookingsDynamicsReport, err)
	return _c
}

func (_c *MockReportService_GetBookingsDynamicsReport_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string) (*response.BookingsDynamicsReport, error)) *MockReportService_GetBookingsDynamicsReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsDynamicsReportPDF provides a mock function for the type MockReportService
func (_mock *MockReportService) GetBookingsDynamicsReportPDF(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string) ([]byte, error) {
	ret := _mock.Called(userID, from, to, hallID, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsDynamicsReportPDF")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string) ([]byte, error)); ok {
		return returnFunc(userID, from, to, hallID, groupBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string) []byte); ok {
		r0 = returnFunc(userID, from, to, hallID, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, string) error); ok {
		r1 = returnFunc(userID, from, to, hallID, groupBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetBookingsDynamicsReportPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsDynamicsReportPDF'
type MockReportService_GetBookingsDynamicsReportPDF_Call struct {
	*mock.Call
}

// GetBookingsDynamicsReportPDF is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - groupBy string
func (_e *MockReportService_Expecter) GetBookingsDynamicsReportPDF(userID interface{}, from interface{}, to interface{}, hallID interface{}, groupBy interface{}) *MockReportService_GetBookingsDynamicsReportPDF_Call {
	return &MockReportService_GetBookingsDynamicsReportPDF_Call{Call: _e.mock.On("GetBookingsDynamicsReportPDF", userID, from, to, hallID, groupBy)}
}

func (_c *MockReportService_GetBookingsDynamicsReportPDF_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string)) *MockReportService_GetBookingsDynamicsReportPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReportService_GetBookingsDynamicsReportPDF_Call) Return(bytes []byte, err error) *MockReportService_GetBookingsDynamicsReportPDF_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReportService_GetBookingsDynamicsReportPDF_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string) ([]byte, error)) *MockReportService_GetBookingsDynamicsReportPDF_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientsReport provides a mock function for the type MockReportService
func (_mock *MockReportService) GetClientsReport(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64) (*response.ClientsReport, error) {
	ret := _mock.Called(userID, from, to, hallID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetClientsReport")
	}

	var r0 *response.ClientsReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, uint64) (*response.ClientsReport, error)); ok {
		return returnFunc(userID, from, to, hallID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, uint64) *response.ClientsReport); ok {
		r0 = returnFunc(userID, from, to, hallID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ClientsReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, uint64) error); ok {
		r1 = returnFunc(userID, from, to, hallID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetClientsReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientsReport'
type MockReportService_GetClientsReport_Call struct {
	*mock.Call
}

// GetClientsReport is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - limit uint64
func (_e *MockReportService_Expecter) GetClientsReport(userID interface{}, from interface{}, to interface{}, hallID interface{}, limit interface{}) *MockReportService_GetClientsReport_Call {
	return &MockReportService_GetClientsReport_Call{Call: _e.mock.On("GetClientsReport", userID, from, to, hallID, limit)}
}

func (_c *MockReportService_GetClientsReport_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64)) *MockReportService_GetClientsReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReportService_GetClientsReport_Call) Return(clientsReport *response.ClientsReport, err error) *MockReportService_GetClientsReport_Call {
	_c.Call.Return(clientsReport, err)
	return _c
}

func (_c *MockReportService_GetClientsReport_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64) (*response.ClientsReport, error)) *MockReportService_GetClientsReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientsReportPDF provides a mock function for the type MockReportService
func (_mock *MockReportService) GetClientsReportPDF(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64) ([]byte, error) {
	ret := _mock.Called(userID, from, to, hallID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetClientsReportPDF")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, uint64) ([]byte, error)); ok {
		return returnFunc(userID, from, to, hallID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, uint64) []byte); ok {
		r0 = returnFunc(userID, from, to, hallID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, uint64) error); ok {
		r1 = returnFunc(userID, from, to, hallID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetClientsReportPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientsReportPDF'
type MockReportService_GetClientsReportPDF_Call struct {
	*mock.Call
}

// GetClientsReportPDF is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - limit uint64
func (_e *MockReportService_Expecter) GetClientsReportPDF(userID interface{}, from interface{}, to interface{}, hallID interface{}, limit interface{}) *MockReportService_GetClientsReportPDF_Call {
	return &MockReportService_GetClientsReportPDF_Call{Call: _e.mock.On("GetClientsReportPDF", userID, from, to, hallID, limit)}
}

func (_c *MockReportService_GetClientsReportPDF_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64)) *MockReportService_GetClientsReportPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReportService_GetClientsReportPDF_Call) Return(bytes []byte, err error) *MockReportService_GetClientsReportPDF_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReportService_GetClientsReportPDF_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64) ([]byte, error)) *MockReportService_GetClientsReportPDF_Call {
	_c.Call.Return(run)
	return _c
}

// GetHallsLoadReport provides a mock function for the type MockReportService
func (_mock *MockReportService) GetHallsLoadReport(userID uint64, from time.Time, to time.Time, hallID *uint64) (*response.HallsLoadReport, error) {
	ret := _mock.Called(userID, from, to, hallID)

	if len(ret) == 0 {
		panic("no return value specified for GetHallsLoadReport")
	}

	var r0 *response.HallsLoadReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64) (*response.HallsLoadReport, error)); ok {
		return returnFunc(userID, from, to, hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64) *response.HallsLoadReport); ok {
		r0 = returnFunc(userID, from, to, hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.HallsLoadReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64) error); ok {
		r1 = returnFunc(userID, from, to, hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetHallsLoadReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHallsLoadReport'
type MockReportService_GetHallsLoadReport_Call struct {
	*mock.Call
}

// GetHallsLoadReport is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
func (_e *MockReportService_Expecter) GetHallsLoadReport(userID interface{}, from interface{}, to interface{}, hallID interface{}) *MockReportService_GetHallsLoadReport_Call {
	return &MockReportService_GetHallsLoadReport_Call{Call: _e.mock.On("GetHallsLoadReport", userID, from, to, hallID)}
}

func (_c *MockReportService_GetHallsLoadReport_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64)) *MockReportService_GetHallsLoadReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReportService_GetHallsLoadReport_Call) Return(hallsLoadReport *response.HallsLoadReport, err error) *MockReportService_GetHallsLoadReport_Call {
	_c.Call.Return(hallsLoadReport, err)
	return _c
}

func (_c *MockReportService_GetHallsLoadReport_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64) (*response.HallsLoadReport, error)) *MockReportService_GetHallsLoadReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetHallsLoadReportPDF provides a mock function for the type MockReportService
func (_mock *MockReportService) GetHallsLoadReportPDF(userID uint64, from time.Time, to time.Time, hallID *uint64) ([]byte, error) {
	ret := _mock.Called(userID, from, to, hallID)

	if len(ret) == 0 {
		panic("no return value specified for GetHallsLoadReportPDF")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64) ([]byte, error)); ok {
		return returnFunc(userID, from, to, hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64) []byte); ok {
		r0 = returnFunc(userID, from, to, hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64) error); ok {
		r1 = returnFunc(userID, from, to, hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetHallsLoadReportPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHallsLoadReportPDF'
type MockReportService_GetHallsLoadReportPDF_Call struct {
	*mock.Call
}

// GetHallsLoadReportPDF is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
func (_e *MockReportService_Expecter) GetHallsLoadReportPDF(userID interface{}, from interface{}, to interface{}, hallID interface{}) *MockReportService_GetHallsLoadReportPDF_Call {
	return &MockReportService_GetHallsLoadReportPDF_Call{Call: _e.mock.On("GetHallsLoadReportPDF", userID, from, to, hallID)}
}

func (_c *MockReportService_GetHallsLoadReportPDF_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64)) *MockReportService_GetHallsLoadReportPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReportService_GetHallsLoadReportPDF_Call) Return(bytes []byte, err error) *MockReportService_GetHallsLoadReportPDF_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReportService_GetHallsLoadReportPDF_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64) ([]byte, error)) *MockReportService_GetHallsLoadReportPDF_Call {
	_c.Call.Return(run)
	return _c
}

// GetSalesReport provides a mock function for the type MockReportService
func (_mock *MockReportService) GetSalesReport(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string) (*response.SalesReport, error) {
	ret := _mock.Called(userID, from, to, hallID, groupBy, metrics)

	if len(ret) == 0 {
		panic("no return value specified for GetSalesReport")
	}

	var r0 *response.SalesReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string, []string) (*response.SalesReport, error)); ok {
		return returnFunc(userID, from, to, hallID, groupBy, metrics)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string, []string) *response.SalesReport); ok {
		r0 = returnFunc(userID, from, to, hallID, groupBy, metrics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.SalesReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, string, []string) error); ok {
		r1 = returnFunc(userID, from, to, hallID, groupBy, metrics)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetSalesReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSalesReport'
type MockReportService_GetSalesReport_Call struct {
	*mock.Call
}

// GetSalesReport is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - groupBy string
//   - metrics []string
func (_e *MockReportService_Expecter) GetSalesReport(userID interface{}, from interface{}, to interface{}, hallID interface{}, groupBy interface{}, metrics interface{}) *MockReportService_GetSalesReport_Call {
	return &MockReportService_GetSalesReport_Call{Call: _e.mock.On("GetSalesReport", userID, from, to, hallID, groupBy, metrics)}
}

func (_c *MockReportService_GetSalesReport_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string)) *MockReportService_GetSalesReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockReportService_GetSalesReport_Call) Return(salesReport *response.SalesReport, err error) *MockReportService_GetSalesReport_Call {
	_c.Call.Return(salesReport, err)
	return _c
}

func (_c *MockReportService_GetSalesReport_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string) (*response.SalesReport, error)) *MockReportService_GetSalesReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetSalesReportPDF provides a mock function for the type MockReportService
func (_mock *MockReportService) GetSalesReportPDF(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string) ([]byte, error) {
	ret := _mock.Called(userID, from, to, hallID, groupBy, metrics)

	if len(ret) == 0 {
		panic("no return value specified for GetSalesReportPDF")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string, []string) ([]byte, error)); ok {
		return returnFunc(userID, from, to, hallID, groupBy, metrics)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string, []string) []byte); ok {
		r0 = returnFunc(userID, from, to, hallID, groupBy, metrics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, string, []string) error); ok {
		r1 = returnFunc(userID, from, to, hallID, groupBy, metrics)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetSalesReportPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSalesReportPDF'
type MockReportService_GetSalesReportPDF_Call struct {
	*mock.Call
}

// GetSalesReportPDF is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - groupBy string
//   - metrics []string
func (_e *MockReportService_Expecter) GetSalesReportPDF(userID interface{}, from interface{}, to interface{}, hallID interface{}, groupBy interface{}, metrics interface{}) *MockReportService_GetSalesReportPDF_Call {
	return &MockReportService_GetSalesReportPDF_Call{Call: _e.mock.On("GetSalesReportPDF", userID, from, to, hallID, groupBy, metrics)}
}

func (_c *MockReportService_GetSalesReportPDF_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string)) *MockReportService_GetSalesReportPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockReportService_GetSalesReportPDF_Call) Return(bytes []byte, err error) *MockReportService_GetSalesReportPDF_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReportService_GetSalesReportPDF_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string) ([]byte, error)) *MockReportService_GetSalesReportPDF_Call {
	_c.Call.Return(run)
	return _c
}
