// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	"college-graduation-project-backend/internal/model"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserDatabase creates a new instance of MockUserDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserDatabase {
	mock := &MockUserDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserDatabase is an autogenerated mock type for the UserDatabase type
type MockUserDatabase struct {
	mock.Mock
}

type MockUserDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserDatabase) EXPECT() *MockUserDatabase_Expecter {
	return &MockUserDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) Create(user *model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *model.User
func (_e *MockUserDatabase_Expecter) Create(user interface{}) *MockUserDatabase_Create_Call {
	return &MockUserDatabase_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUserDatabase_Create_Call) Run(run func(user *model.User)) *MockUserDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_Create_Call) Return(err error) *MockUserDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserDatabase_Create_Call) RunAndReturn(run func(user *model.User) error) *MockUserDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockUserDatabase_Expecter) Delete(id interface{}) *MockUserDatabase_Delete_Call {
	return &MockUserDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockUserDatabase_Delete_Call) Run(run func(id uint64)) *MockUserDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_Delete_Call) Return(err error) *MockUserDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockUserDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) FindAll() ([]model.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDatabase_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserDatabase_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockUserDatabase_Expecter) FindAll() *MockUserDatabase_FindAll_Call {
	return &MockUserDatabase_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockUserDatabase_FindAll_Call) Run(run func()) *MockUserDatabase_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserDatabase_FindAll_Call) Return(users []model.User, err error) *MockUserDatabase_FindAll_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserDatabase_FindAll_Call) RunAndReturn(run func() ([]model.User, error)) *MockUserDatabase_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) FindByEmail(email string) (*model.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDatabase_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserDatabase_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserDatabase_Expecter) FindByEmail(email interface{}) *MockUserDatabase_FindByEmail_Call {
	return &MockUserDatabase_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *MockUserDatabase_FindByEmail_Call) Run(run func(email string)) *MockUserDatabase_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_FindByEmail_Call) Return(user *model.User, err error) *MockUserDatabase_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserDatabase_FindByEmail_Call) RunAndReturn(run func(email string) (*model.User, error)) *MockUserDatabase_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) FindByID(id uint64) (*model.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserDatabase_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserDatabase_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockUserDatabase_Expecter) FindByID(id interface{}) *MockUserDatabase_FindByID_Call {
	return &MockUserDatabase_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockUserDatabase_FindByID_Call) Run(run func(id uint64)) *MockUserDatabase_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_FindByID_Call) Return(user *model.User, err error) *MockUserDatabase_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserDatabase_FindByID_Call) RunAndReturn(run func(id uint64) (*model.User, error)) *MockUserDatabase_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserDatabase
func (_mock *MockUserDatabase) Update(user *model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *model.User
func (_e *MockUserDatabase_Expecter) Update(user interface{}) *MockUserDatabase_Update_Call {
	return &MockUserDatabase_Update_Call{Call: _e.mock.On("Update", user)}
}

func (_c *MockUserDatabase_Update_Call) Run(run func(user *model.User)) *MockUserDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserDatabase_Update_Call) Return(err error) *MockUserDatabase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserDatabase_Update_Call) RunAndReturn(run func(user *model.User) error) *MockUserDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHallDatabase creates a new instance of MockHallDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHallDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHallDatabase {
	mock := &MockHallDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHallDatabase is an autogenerated mock type for the HallDatabase type
type MockHallDatabase struct {
	mock.Mock
}

type MockHallDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHallDatabase) EXPECT() *MockHallDatabase_Expecter {
	return &MockHallDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) Create(hall *model.Hall) error {
	ret := _mock.Called(hall)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Hall) error); ok {
		r0 = returnFunc(hall)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHallDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHallDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - hall *model.Hall
func (_e *MockHallDatabase_Expecter) Create(hall interface{}) *MockHallDatabase_Create_Call {
	return &MockHallDatabase_Create_Call{Call: _e.mock.On("Create", hall)}
}

func (_c *MockHallDatabase_Create_Call) Run(run func(hall *model.Hall)) *MockHallDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Hall
		if args[0] != nil {
			arg0 = args[0].(*model.Hall)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallDatabase_Create_Call) Return(err error) *MockHallDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHallDatabase_Create_Call) RunAndReturn(run func(hall *model.Hall) error) *MockHallDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHallDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHallDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockHallDatabase_Expecter) Delete(id interface{}) *MockHallDatabase_Delete_Call {
	return &MockHallDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockHallDatabase_Delete_Call) Run(run func(id uint64)) *MockHallDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallDatabase_Delete_Call) Return(err error) *MockHallDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHallDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockHallDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) FindAll() ([]model.Hall, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Hall, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Hall); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallDatabase_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockHallDatabase_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockHallDatabase_Expecter) FindAll() *MockHallDatabase_FindAll_Call {
	return &MockHallDatabase_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockHallDatabase_FindAll_Call) Run(run func()) *MockHallDatabase_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHallDatabase_FindAll_Call) Return(halls []model.Hall, err error) *MockHallDatabase_FindAll_Call {
	_c.Call.Return(halls, err)
	return _c
}

func (_c *MockHallDatabase_FindAll_Call) RunAndReturn(run func() ([]model.Hall, error)) *MockHallDatabase_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllActive provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) FindAllActive() ([]model.Hall, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllActive")
	}

	var r0 []model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Hall, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Hall); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallDatabase_FindAllActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllActive'
type MockHallDatabase_FindAllActive_Call struct {
	*mock.Call
}

// FindAllActive is a helper method to define mock.On call
func (_e *MockHallDatabase_Expecter) FindAllActive() *MockHallDatabase_FindAllActive_Call {
	return &MockHallDatabase_FindAllActive_Call{Call: _e.mock.On("FindAllActive")}
}

func (_c *MockHallDatabase_FindAllActive_Call) Run(run func()) *MockHallDatabase_FindAllActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHallDatabase_FindAllActive_Call) Return(halls []model.Hall, err error) *MockHallDatabase_FindAllActive_Call {
	_c.Call.Return(halls, err)
	return _c
}

func (_c *MockHallDatabase_FindAllActive_Call) RunAndReturn(run func() ([]model.Hall, error)) *MockHallDatabase_FindAllActive_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) FindByID(id uint64) (*model.Hall, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Hall, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Hall); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallDatabase_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHallDatabase_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockHallDatabase_Expecter) FindByID(id interface{}) *MockHallDatabase_FindByID_Call {
	return &MockHallDatabase_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockHallDatabase_FindByID_Call) Run(run func(id uint64)) *MockHallDatabase_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallDatabase_FindByID_Call) Return(hall *model.Hall, err error) *MockHallDatabase_FindByID_Call {
	_c.Call.Return(hall, err)
	return _c
}

func (_c *MockHallDatabase_FindByID_Call) RunAndReturn(run func(id uint64) (*model.Hall, error)) *MockHallDatabase_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockHallDatabase
func (_mock *MockHallDatabase) Update(hall *model.Hall) error {
	ret := _mock.Called(hall)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Hall) error); ok {
		r0 = returnFunc(hall)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHallDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHallDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - hall *model.Hall
func (_e *MockHallDatabase_Expecter) Update(hall interface{}) *MockHallDatabase_Update_Call {
	return &MockHallDatabase_Update_Call{Call: _e.mock.On("Update", hall)}
}

func (_c *MockHallDatabase_Update_Call) Run(run func(hall *model.Hall)) *MockHallDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Hall
		if args[0] != nil {
			arg0 = args[0].(*model.Hall)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallDatabase_Update_Call) Return(err error) *MockHallDatabase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHallDatabase_Update_Call) RunAndReturn(run func(hall *model.Hall) error) *MockHallDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReviewDatabase creates a new instance of MockReviewDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewDatabase {
	mock := &MockReviewDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewDatabase is an autogenerated mock type for the ReviewDatabase type
type MockReviewDatabase struct {
	mock.Mock
}

type MockReviewDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewDatabase) EXPECT() *MockReviewDatabase_Expecter {
	return &MockReviewDatabase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) Create(review *model.Review) error {
	ret := _mock.Called(review)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Review) error); ok {
		r0 = returnFunc(review)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReviewDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - review *model.Review
func (_e *MockReviewDatabase_Expecter) Create(review interface{}) *MockReviewDatabase_Create_Call {
	return &MockReviewDatabase_Create_Call{Call: _e.mock.On("Create", review)}
}

func (_c *MockReviewDatabase_Create_Call) Run(run func(review *model.Review)) *MockReviewDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Review
		if args[0] != nil {
			arg0 = args[0].(*model.Review)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_Create_Call) Return(err error) *MockReviewDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewDatabase_Create_Call) RunAndReturn(run func(review *model.Review) error) *MockReviewDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReviewDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockReviewDatabase_Expecter) Delete(id interface{}) *MockReviewDatabase_Delete_Call {
	return &MockReviewDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockReviewDatabase_Delete_Call) Run(run func(id uint64)) *MockReviewDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_Delete_Call) Return(err error) *MockReviewDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockReviewDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindAll() ([]model.Review, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Review, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Review); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockReviewDatabase_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockReviewDatabase_Expecter) FindAll() *MockReviewDatabase_FindAll_Call {
	return &MockReviewDatabase_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockReviewDatabase_FindAll_Call) Run(run func()) *MockReviewDatabase_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReviewDatabase_FindAll_Call) Return(reviews []model.Review, err error) *MockReviewDatabase_FindAll_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewDatabase_FindAll_Call) RunAndReturn(run func() ([]model.Review, error)) *MockReviewDatabase_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllWithFilters provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindAllWithFilters(hallID *uint64, minRating *uint64) ([]model.Review, error) {
	ret := _mock.Called(hallID, minRating)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithFilters")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) ([]model.Review, error)); ok {
		return returnFunc(hallID, minRating)
	}
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) []model.Review); ok {
		r0 = returnFunc(hallID, minRating)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*uint64, *uint64) error); ok {
		r1 = returnFunc(hallID, minRating)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindAllWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithFilters'
type MockReviewDatabase_FindAllWithFilters_Call struct {
	*mock.Call
}

// FindAllWithFilters is a helper method to define mock.On call
//   - hallID *uint64
//   - minRating *uint64
func (_e *MockReviewDatabase_Expecter) FindAllWithFilters(hallID interface{}, minRating interface{}) *MockReviewDatabase_FindAllWithFilters_Call {
	return &MockReviewDatabase_FindAllWithFilters_Call{Call: _e.mock.On("FindAllWithFilters", hallID, minRating)}
}

func (_c *MockReviewDatabase_FindAllWithFilters_Call) Run(run func(hallID *uint64, minRating *uint64)) *MockReviewDatabase_FindAllWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *uint64
		if args[0] != nil {
			arg0 = args[0].(*uint64)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindAllWithFilters_Call) Return(reviews []model.Review, err error) *MockReviewDatabase_FindAllWithFilters_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewDatabase_FindAllWithFilters_Call) RunAndReturn(run func(hallID *uint64, minRating *uint64) ([]model.Review, error)) *MockReviewDatabase_FindAllWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// FindByBookingID provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindByBookingID(bookingID uint64) (*model.Review, error) {
	ret := _mock.Called(bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindByBookingID")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Review, error)); ok {
		return returnFunc(bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Review); ok {
		r0 = returnFunc(bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindByBookingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByBookingID'
type MockReviewDatabase_FindByBookingID_Call struct {
	*mock.Call
}

// FindByBookingID is a helper method to define mock.On call
//   - bookingID uint64
func (_e *MockReviewDatabase_Expecter) FindByBookingID(bookingID interface{}) *MockReviewDatabase_FindByBookingID_Call {
	return &MockReviewDatabase_FindByBookingID_Call{Call: _e.mock.On("FindByBookingID", bookingID)}
}

func (_c *MockReviewDatabase_FindByBookingID_Call) Run(run func(bookingID uint64)) *MockReviewDatabase_FindByBookingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindByBookingID_Call) Return(review *model.Review, err error) *MockReviewDatabase_FindByBookingID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewDatabase_FindByBookingID_Call) RunAndReturn(run func(bookingID uint64) (*model.Review, error)) *MockReviewDatabase_FindByBookingID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHallID provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindByHallID(hallID uint64) ([]model.Review, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for FindByHallID")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) ([]model.Review, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) []model.Review); ok {
		r0 = returnFunc(hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindByHallID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHallID'
type MockReviewDatabase_FindByHallID_Call struct {
	*mock.Call
}

// FindByHallID is a helper method to define mock.On call
//   - hallID uint64
func (_e *MockReviewDatabase_Expecter) FindByHallID(hallID interface{}) *MockReviewDatabase_FindByHallID_Call {
	return &MockReviewDatabase_FindByHallID_Call{Call: _e.mock.On("FindByHallID", hallID)}
}

func (_c *MockReviewDatabase_FindByHallID_Call) Run(run func(hallID uint64)) *MockReviewDatabase_FindByHallID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindByHallID_Call) Return(reviews []model.Review, err error) *MockReviewDatabase_FindByHallID_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewDatabase_FindByHallID_Call) RunAndReturn(run func(hallID uint64) ([]model.Review, error)) *MockReviewDatabase_FindByHallID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindByID(id uint64) (*model.Review, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Review, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Review); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockReviewDatabase_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockReviewDatabase_Expecter) FindByID(id interface{}) *MockReviewDatabase_FindByID_Call {
	return &MockReviewDatabase_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockReviewDatabase_FindByID_Call) Run(run func(id uint64)) *MockReviewDatabase_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindByID_Call) Return(review *model.Review, err error) *MockReviewDatabase_FindByID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewDatabase_FindByID_Call) RunAndReturn(run func(id uint64) (*model.Review, error)) *MockReviewDatabase_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserIDAndBookingID provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) FindByUserIDAndBookingID(userID uint64, bookingID uint64) (*model.Review, error) {
	ret := _mock.Called(userID, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserIDAndBookingID")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*model.Review, error)); ok {
		return returnFunc(userID, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *model.Review); ok {
		r0 = returnFunc(userID, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = returnFunc(userID, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewDatabase_FindByUserIDAndBookingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserIDAndBookingID'
type MockReviewDatabase_FindByUserIDAndBookingID_Call struct {
	*mock.Call
}

// FindByUserIDAndBookingID is a helper method to define mock.On call
//   - userID uint64
//   - bookingID uint64
func (_e *MockReviewDatabase_Expecter) FindByUserIDAndBookingID(userID interface{}, bookingID interface{}) *MockReviewDatabase_FindByUserIDAndBookingID_Call {
	return &MockReviewDatabase_FindByUserIDAndBookingID_Call{Call: _e.mock.On("FindByUserIDAndBookingID", userID, bookingID)}
}

func (_c *MockReviewDatabase_FindByUserIDAndBookingID_Call) Run(run func(userID uint64, bookingID uint64)) *MockReviewDatabase_FindByUserIDAndBookingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_FindByUserIDAndBookingID_Call) Return(review *model.Review, err error) *MockReviewDatabase_FindByUserIDAndBookingID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewDatabase_FindByUserIDAndBookingID_Call) RunAndReturn(run func(userID uint64, bookingID uint64) (*model.Review, error)) *MockReviewDatabase_FindByUserIDAndBookingID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockReviewDatabase
func (_mock *MockReviewDatabase) Update(review *model.Review) error {
	ret := _mock.Called(review)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Review) error); ok {
		r0 = returnFunc(review)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockReviewDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - review *model.Review
func (_e *MockReviewDatabase_Expecter) Update(review interface{}) *MockReviewDatabase_Update_Call {
	return &MockReviewDatabase_Update_Call{Call: _e.mock.On("Update", review)}
}

func (_c *MockReviewDatabase_Update_Call) Run(run func(review *model.Review)) *MockReviewDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Review
		if args[0] != nil {
			arg0 = args[0].(*model.Review)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewDatabase_Update_Call) Return(err error) *MockReviewDatabase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewDatabase_Update_Call) RunAndReturn(run func(review *model.Review) error) *MockReviewDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageDatabase creates a new instance of MockImageDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageDatabase {
	mock := &MockImageDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageDatabase is an autogenerated mock type for the ImageDatabase type
type MockImageDatabase struct {
	mock.Mock
}

type MockImageDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageDatabase) EXPECT() *MockImageDatabase_Expecter {
	return &MockImageDatabase_Expecter{mock: &_m.Mock}
}

// AttachToHall provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) AttachToHall(hallID uint64, imageID uint64) error {
	ret := _mock.Called(hallID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for AttachToHall")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = returnFunc(hallID, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_AttachToHall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachToHall'
type MockImageDatabase_AttachToHall_Call struct {
	*mock.Call
}

// AttachToHall is a helper method to define mock.On call
//   - hallID uint64
//   - imageID uint64
func (_e *MockImageDatabase_Expecter) AttachToHall(hallID interface{}, imageID interface{}) *MockImageDatabase_AttachToHall_Call {
	return &MockImageDatabase_AttachToHall_Call{Call: _e.mock.On("AttachToHall", hallID, imageID)}
}

func (_c *MockImageDatabase_AttachToHall_Call) Run(run func(hallID uint64, imageID uint64)) *MockImageDatabase_AttachToHall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageDatabase_AttachToHall_Call) Return(err error) *MockImageDatabase_AttachToHall_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_AttachToHall_Call) RunAndReturn(run func(hallID uint64, imageID uint64) error) *MockImageDatabase_AttachToHall_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) Create(image *model.Image) error {
	ret := _mock.Called(image)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Image) error); ok {
		r0 = returnFunc(image)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockImageDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - image *model.Image
func (_e *MockImageDatabase_Expecter) Create(image interface{}) *MockImageDatabase_Create_Call {
	return &MockImageDatabase_Create_Call{Call: _e.mock.On("Create", image)}
}

func (_c *MockImageDatabase_Create_Call) Run(run func(image *model.Image)) *MockImageDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Image
		if args[0] != nil {
			arg0 = args[0].(*model.Image)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_Create_Call) Return(err error) *MockImageDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_Create_Call) RunAndReturn(run func(image *model.Image) error) *MockImageDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockImageDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockImageDatabase_Expecter) Delete(id interface{}) *MockImageDatabase_Delete_Call {
	return &MockImageDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockImageDatabase_Delete_Call) Run(run func(id uint64)) *MockImageDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_Delete_Call) Return(err error) *MockImageDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockImageDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByHallID provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) FindByHallID(hallID uint64) ([]model.Image, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for FindByHallID")
	}

	var r0 []model.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) ([]model.Image, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) []model.Image); ok {
		r0 = returnFunc(hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageDatabase_FindByHallID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByHallID'
type MockImageDatabase_FindByHallID_Call struct {
	*mock.Call
}

// FindByHallID is a helper method to define mock.On call
//   - hallID uint64
func (_e *MockImageDatabase_Expecter) FindByHallID(hallID interface{}) *MockImageDatabase_FindByHallID_Call {
	return &MockImageDatabase_FindByHallID_Call{Call: _e.mock.On("FindByHallID", hallID)}
}

func (_c *MockImageDatabase_FindByHallID_Call) Run(run func(hallID uint64)) *MockImageDatabase_FindByHallID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_FindByHallID_Call) Return(images []model.Image, err error) *MockImageDatabase_FindByHallID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageDatabase_FindByHallID_Call) RunAndReturn(run func(hallID uint64) ([]model.Image, error)) *MockImageDatabase_FindByHallID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) GetByID(id uint64) (*model.Image, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Image, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Image); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageDatabase_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockImageDatabase_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockImageDatabase_Expecter) GetByID(id interface{}) *MockImageDatabase_GetByID_Call {
	return &MockImageDatabase_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockImageDatabase_GetByID_Call) Run(run func(id uint64)) *MockImageDatabase_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_GetByID_Call) Return(image *model.Image, err error) *MockImageDatabase_GetByID_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageDatabase_GetByID_Call) RunAndReturn(run func(id uint64) (*model.Image, error)) *MockImageDatabase_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) GetByUserID(userID uint64) (*model.Image, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *model.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Image, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Image); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageDatabase_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockImageDatabase_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - userID uint64
func (_e *MockImageDatabase_Expecter) GetByUserID(userID interface{}) *MockImageDatabase_GetByUserID_Call {
	return &MockImageDatabase_GetByUserID_Call{Call: _e.mock.On("GetByUserID", userID)}
}

func (_c *MockImageDatabase_GetByUserID_Call) Run(run func(userID uint64)) *MockImageDatabase_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_GetByUserID_Call) Return(image *model.Image, err error) *MockImageDatabase_GetByUserID_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageDatabase_GetByUserID_Call) RunAndReturn(run func(userID uint64) (*model.Image, error)) *MockImageDatabase_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserImage provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) RemoveUserImage(userID uint64) error {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_RemoveUserImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserImage'
type MockImageDatabase_RemoveUserImage_Call struct {
	*mock.Call
}

// RemoveUserImage is a helper method to define mock.On call
//   - userID uint64
func (_e *MockImageDatabase_Expecter) RemoveUserImage(userID interface{}) *MockImageDatabase_RemoveUserImage_Call {
	return &MockImageDatabase_RemoveUserImage_Call{Call: _e.mock.On("RemoveUserImage", userID)}
}

func (_c *MockImageDatabase_RemoveUserImage_Call) Run(run func(userID uint64)) *MockImageDatabase_RemoveUserImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageDatabase_RemoveUserImage_Call) Return(err error) *MockImageDatabase_RemoveUserImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_RemoveUserImage_Call) RunAndReturn(run func(userID uint64) error) *MockImageDatabase_RemoveUserImage_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserImage provides a mock function for the type MockImageDatabase
func (_mock *MockImageDatabase) SetUserImage(userID uint64, imageID uint64) error {
	ret := _mock.Called(userID, imageID)

	if len(ret) == 0 {
		panic("no return value specified for SetUserImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = returnFunc(userID, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageDatabase_SetUserImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserImage'
type MockImageDatabase_SetUserImage_Call struct {
	*mock.Call
}

// SetUserImage is a helper method to define mock.On call
//   - userID uint64
//   - imageID uint64
func (_e *MockImageDatabase_Expecter) SetUserImage(userID interface{}, imageID interface{}) *MockImageDatabase_SetUserImage_Call {
	return &MockImageDatabase_SetUserImage_Call{Call: _e.mock.On("SetUserImage", userID, imageID)}
}

func (_c *MockImageDatabase_SetUserImage_Call) Run(run func(userID uint64, imageID uint64)) *MockImageDatabase_SetUserImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageDatabase_SetUserImage_Call) Return(err error) *MockImageDatabase_SetUserImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageDatabase_SetUserImage_Call) RunAndReturn(run func(userID uint64, imageID uint64) error) *MockImageDatabase_SetUserImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingDatabase creates a new instance of MockBookingDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingDatabase {
	mock := &MockBookingDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingDatabase is an autogenerated mock type for the BookingDatabase type
type MockBookingDatabase struct {
	mock.Mock
}

type MockBookingDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingDatabase) EXPECT() *MockBookingDatabase_Expecter {
	return &MockBookingDatabase_Expecter{mock: &_m.Mock}
}

// CheckConflict provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) CheckConflict(hallID uint64, startDateTime time.Time, endDateTime time.Time) (bool, error) {
	ret := _mock.Called(hallID, startDateTime, endDateTime)

	if len(ret) == 0 {
		panic("no return value specified for CheckConflict")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) (bool, error)); ok {
		return returnFunc(hallID, startDateTime, endDateTime)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) bool); ok {
		r0 = returnFunc(hallID, startDateTime, endDateTime)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time) error); ok {
		r1 = returnFunc(hallID, startDateTime, endDateTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_CheckConflict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckConflict'
type MockBookingDatabase_CheckConflict_Call struct {
	*mock.Call
}

// CheckConflict is a helper method to define mock.On call
//   - hallID uint64
//   - startDateTime time.Time
//   - endDateTime time.Time
func (_e *MockBookingDatabase_Expecter) CheckConflict(hallID interface{}, startDateTime interface{}, endDateTime interface{}) *MockBookingDatabase_CheckConflict_Call {
	return &MockBookingDatabase_CheckConflict_Call{Call: _e.mock.On("CheckConflict", hallID, startDateTime, endDateTime)}
}

func (_c *MockBookingDatabase_CheckConflict_Call) Run(run func(hallID uint64, startDateTime time.Time, endDateTime time.Time)) *MockBookingDatabase_CheckConflict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_CheckConflict_Call) Return(b bool, err error) *MockBookingDatabase_CheckConflict_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBookingDatabase_CheckConflict_Call) RunAndReturn(run func(hallID uint64, startDateTime time.Time, endDateTime time.Time) (bool, error)) *MockBookingDatabase_CheckConflict_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) Create(booking *model.Booking) error {
	ret := _mock.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Booking) error); ok {
		r0 = returnFunc(booking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingDatabase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingDatabase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - booking *model.Booking
func (_e *MockBookingDatabase_Expecter) Create(booking interface{}) *MockBookingDatabase_Create_Call {
	return &MockBookingDatabase_Create_Call{Call: _e.mock.On("Create", booking)}
}

func (_c *MockBookingDatabase_Create_Call) Run(run func(booking *model.Booking)) *MockBookingDatabase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Booking
		if args[0] != nil {
			arg0 = args[0].(*model.Booking)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_Create_Call) Return(err error) *MockBookingDatabase_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingDatabase_Create_Call) RunAndReturn(run func(booking *model.Booking) error) *MockBookingDatabase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingDatabase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBookingDatabase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockBookingDatabase_Expecter) Delete(id interface{}) *MockBookingDatabase_Delete_Call {
	return &MockBookingDatabase_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockBookingDatabase_Delete_Call) Run(run func(id uint64)) *MockBookingDatabase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_Delete_Call) Return(err error) *MockBookingDatabase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingDatabase_Delete_Call) RunAndReturn(run func(id uint64) error) *MockBookingDatabase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) FindAll(hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time) ([]model.Booking, error) {
	ret := _mock.Called(hallID, bookingUserID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64, *time.Time, *time.Time) ([]model.Booking, error)); ok {
		return returnFunc(hallID, bookingUserID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64, *time.Time, *time.Time) []model.Booking); ok {
		r0 = returnFunc(hallID, bookingUserID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*uint64, *uint64, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(hallID, bookingUserID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBookingDatabase_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - hallID *uint64
//   - bookingUserID *uint64
//   - from *time.Time
//   - to *time.Time
func (_e *MockBookingDatabase_Expecter) FindAll(hallID interface{}, bookingUserID interface{}, from interface{}, to interface{}) *MockBookingDatabase_FindAll_Call {
	return &MockBookingDatabase_FindAll_Call{Call: _e.mock.On("FindAll", hallID, bookingUserID, from, to)}
}

func (_c *MockBookingDatabase_FindAll_Call) Run(run func(hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time)) *MockBookingDatabase_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *uint64
		if args[0] != nil {
			arg0 = args[0].(*uint64)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_FindAll_Call) Return(bookings []model.Booking, err error) *MockBookingDatabase_FindAll_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingDatabase_FindAll_Call) RunAndReturn(run func(hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time) ([]model.Booking, error)) *MockBookingDatabase_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllFromUser provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) FindAllFromUser(userID uint64, from *time.Time, to *time.Time) ([]model.Booking, error) {
	ret := _mock.Called(userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindAllFromUser")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *time.Time, *time.Time) ([]model.Booking, error)); ok {
		return returnFunc(userID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *time.Time, *time.Time) []model.Booking); ok {
		r0 = returnFunc(userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(userID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_FindAllFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllFromUser'
type MockBookingDatabase_FindAllFromUser_Call struct {
	*mock.Call
}

// FindAllFromUser is a helper method to define mock.On call
//   - userID uint64
//   - from *time.Time
//   - to *time.Time
func (_e *MockBookingDatabase_Expecter) FindAllFromUser(userID interface{}, from interface{}, to interface{}) *MockBookingDatabase_FindAllFromUser_Call {
	return &MockBookingDatabase_FindAllFromUser_Call{Call: _e.mock.On("FindAllFromUser", userID, from, to)}
}

func (_c *MockBookingDatabase_FindAllFromUser_Call) Run(run func(userID uint64, from *time.Time, to *time.Time)) *MockBookingDatabase_FindAllFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_FindAllFromUser_Call) Return(bookings []model.Booking, err error) *MockBookingDatabase_FindAllFromUser_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingDatabase_FindAllFromUser_Call) RunAndReturn(run func(userID uint64, from *time.Time, to *time.Time) ([]model.Booking, error)) *MockBookingDatabase_FindAllFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindBookingsForHall provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) FindBookingsForHall(hallID uint64, from time.Time, to time.Time) ([]model.Booking, error) {
	ret := _mock.Called(hallID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindBookingsForHall")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) ([]model.Booking, error)); ok {
		return returnFunc(hallID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) []model.Booking); ok {
		r0 = returnFunc(hallID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time) error); ok {
		r1 = returnFunc(hallID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_FindBookingsForHall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBookingsForHall'
type MockBookingDatabase_FindBookingsForHall_Call struct {
	*mock.Call
}

// FindBookingsForHall is a helper method to define mock.On call
//   - hallID uint64
//   - from time.Time
//   - to time.Time
func (_e *MockBookingDatabase_Expecter) FindBookingsForHall(hallID interface{}, from interface{}, to interface{}) *MockBookingDatabase_FindBookingsForHall_Call {
	return &MockBookingDatabase_FindBookingsForHall_Call{Call: _e.mock.On("FindBookingsForHall", hallID, from, to)}
}

func (_c *MockBookingDatabase_FindBookingsForHall_Call) Run(run func(hallID uint64, from time.Time, to time.Time)) *MockBookingDatabase_FindBookingsForHall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_FindBookingsForHall_Call) Return(bookings []model.Booking, err error) *MockBookingDatabase_FindBookingsForHall_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingDatabase_FindBookingsForHall_Call) RunAndReturn(run func(hallID uint64, from time.Time, to time.Time) ([]model.Booking, error)) *MockBookingDatabase_FindBookingsForHall_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) FindByID(id uint64) (*model.Booking, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Booking, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Booking); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingDatabase_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBookingDatabase_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockBookingDatabase_Expecter) FindByID(id interface{}) *MockBookingDatabase_FindByID_Call {
	return &MockBookingDatabase_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockBookingDatabase_FindByID_Call) Run(run func(id uint64)) *MockBookingDatabase_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_FindByID_Call) Return(booking *model.Booking, err error) *MockBookingDatabase_FindByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingDatabase_FindByID_Call) RunAndReturn(run func(id uint64) (*model.Booking, error)) *MockBookingDatabase_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBookingDatabase
func (_mock *MockBookingDatabase) Update(booking *model.Booking) error {
	ret := _mock.Called(booking)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Booking) error); ok {
		r0 = returnFunc(booking)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingDatabase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBookingDatabase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - booking *model.Booking
func (_e *MockBookingDatabase_Expecter) Update(booking interface{}) *MockBookingDatabase_Update_Call {
	return &MockBookingDatabase_Update_Call{Call: _e.mock.On("Update", booking)}
}

func (_c *MockBookingDatabase_Update_Call) Run(run func(booking *model.Booking)) *MockBookingDatabase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Booking
		if args[0] != nil {
			arg0 = args[0].(*model.Booking)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBookingDatabase_Update_Call) Return(err error) *MockBookingDatabase_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingDatabase_Update_Call) RunAndReturn(run func(booking *model.Booking) error) *MockBookingDatabase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportDatabase creates a new instance of MockReportDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportDatabase {
	mock := &MockReportDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportDatabase is an autogenerated mock type for the ReportDatabase type
type MockReportDatabase struct {
	mock.Mock
}

type MockReportDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportDatabase) EXPECT() *MockReportDatabase_Expecter {
	return &MockReportDatabase_Expecter{mock: &_m.Mock}
}

// CountHalls provides a mock function for the type MockReportDatabase
func (_mock *MockReportDatabase) CountHalls(hallID *uint64) (uint64, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for CountHalls")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*uint64) (uint64, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(*uint64) uint64); ok {
		r0 = returnFunc(hallID)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(*uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDatabase_CountHalls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountHalls'
type MockReportDatabase_CountHalls_Call struct {
	*mock.Call
}

// CountHalls is a helper method to define mock.On call
//   - hallID *uint64
func (_e *MockReportDatabase_Expecter) CountHalls(hallID interface{}) *MockReportDatabase_CountHalls_Call {
	return &MockReportDatabase_CountHalls_Call{Call: _e.mock.On("CountHalls", hallID)}
}

func (_c *MockReportDatabase_CountHalls_Call) Run(run func(hallID *uint64)) *MockReportDatabase_CountHalls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *uint64
		if args[0] != nil {
			arg0 = args[0].(*uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReportDatabase_CountHalls_Call) Return(v uint64, err error) *MockReportDatabase_CountHalls_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockReportDatabase_CountHalls_Call) RunAndReturn(run func(hallID *uint64) (uint64, error)) *MockReportDatabase_CountHalls_Call {
	_c.Call.Return(run)
	return _c
}

// FindReportBookings provides a mock function for the type MockReportDatabase
func (_mock *MockReportDatabase) FindReportBookings(from time.Time, to time.Time, hallID *uint64) ([]model.Booking, error) {
	ret := _mock.Called(from, to, hallID)

	if len(ret) == 0 {
		panic("no return value specified for FindReportBookings")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time, *uint64) ([]model.Booking, error)); ok {
		return returnFunc(from, to, hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time, *uint64) []model.Booking); ok {
		r0 = returnFunc(from, to, hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time, time.Time, *uint64) error); ok {
		r1 = returnFunc(from, to, hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDatabase_FindReportBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindReportBookings'
type MockReportDatabase_FindReportBookings_Call struct {
	*mock.Call
}

// FindReportBookings is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
func (_e *MockReportDatabase_Expecter) FindReportBookings(from interface{}, to interface{}, hallID interface{}) *MockReportDatabase_FindReportBookings_Call {
	return &MockReportDatabase_FindReportBookings_Call{Call: _e.mock.On("FindReportBookings", from, to, hallID)}
}

func (_c *MockReportDatabase_FindReportBookings_Call) Run(run func(from time.Time, to time.Time, hallID *uint64)) *MockReportDatabase_FindReportBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *uint64
		if args[2] != nil {
			arg2 = args[2].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReportDatabase_FindReportBookings_Call) Return(bookings []model.Booking, err error) *MockReportDatabase_FindReportBookings_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockReportDatabase_FindReportBookings_Call) RunAndReturn(run func(from time.Time, to time.Time, hallID *uint64) ([]model.Booking, error)) *MockReportDatabase_FindReportBookings_Call {
	_c.Call.Return(run)
	return _c
}

// FindSalesBookings provides a mock function for the type MockReportDatabase
func (_mock *MockReportDatabase) FindSalesBookings(from time.Time, to time.Time, hallID *uint64) ([]model.Booking, error) {
	ret := _mock.Called(from, to, hallID)

	if len(ret) == 0 {
		panic("no return value specified for FindSalesBookings")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time, *uint64) ([]model.Booking, error)); ok {
		return returnFunc(from, to, hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time, time.Time, *uint64) []model.Booking); ok {
		r0 = returnFunc(from, to, hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time, time.Time, *uint64) error); ok {
		r1 = returnFunc(from, to, hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportDatabase_FindSalesBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSalesBookings'
type MockReportDatabase_FindSalesBookings_Call struct {
	*mock.Call
}

// FindSalesBookings is a helper method to define mock.On call
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
func (_e *MockReportDatabase_Expecter) FindSalesBookings(from interface{}, to interface{}, hallID interface{}) *MockReportDatabase_FindSalesBookings_Call {
	return &MockReportDatabase_FindSalesBookings_Call{Call: _e.mock.On("FindSalesBookings", from, to, hallID)}
}

func (_c *MockReportDatabase_FindSalesBookings_Call) Run(run func(from time.Time, to time.Time, hallID *uint64)) *MockReportDatabase_FindSalesBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *uint64
		if args[2] != nil {
			arg2 = args[2].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReportDatabase_FindSalesBookings_Call) Return(bookings []model.Booking, err error) *MockReportDatabase_FindSalesBookings_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockReportDatabase_FindSalesBookings_Call) RunAndReturn(run func(from time.Time, to time.Time, hallID *uint64) ([]model.Booking, error)) *MockReportDatabase_FindSalesBookings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserAgreementDatabase creates a new instance of MockUserAgreementDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAgreementDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAgreementDatabase {
	mock := &MockUserAgreementDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAgreementDatabase is an autogenerated mock type for the UserAgreementDatabase type
type MockUserAgreementDatabase struct {
	mock.Mock
}

type MockUserAgreementDatabase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAgreementDatabase) EXPECT() *MockUserAgreementDatabase_Expecter {
	return &MockUserAgreementDatabase_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockUserAgreementDatabase
func (_mock *MockUserAgreementDatabase) Get() (*model.UserAgreement, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.UserAgreement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.UserAgreement, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.UserAgreement); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAgreement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAgreementDatabase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserAgreementDatabase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockUserAgreementDatabase_Expecter) Get() *MockUserAgreementDatabase_Get_Call {
	return &MockUserAgreementDatabase_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockUserAgreementDatabase_Get_Call) Run(run func()) *MockUserAgreementDatabase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserAgreementDatabase_Get_Call) Return(userAgreement *model.UserAgreement, err error) *MockUserAgreementDatabase_Get_Call {
	_c.Call.Return(userAgreement, err)
	return _c
}

func (_c *MockUserAgreementDatabase_Get_Call) RunAndReturn(run func() (*model.UserAgreement, error)) *MockUserAgreementDatabase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserAgreementDatabase
func (_mock *MockUserAgreementDatabase) Save(text string) (*model.UserAgreement, error) {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.UserAgreement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.UserAgreement, error)); ok {
		return returnFunc(text)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.UserAgreement); ok {
		r0 = returnFunc(text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAgreement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAgreementDatabase_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserAgreementDatabase_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - text string
func (_e *MockUserAgreementDatabase_Expecter) Save(text interface{}) *MockUserAgreementDatabase_Save_Call {
	return &MockUserAgreementDatabase_Save_Call{Call: _e.mock.On("Save", text)}
}

func (_c *MockUserAgreementDatabase_Save_Call) Run(run func(text string)) *MockUserAgreementDatabase_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserAgreementDatabase_Save_Call) Return(userAgreement *model.UserAgreement, err error) *MockUserAgreementDatabase_Save_Call {
	_c.Call.Return(userAgreement, err)
	return _c
}

func (_c *MockUserAgreementDatabase_Save_Call) RunAndReturn(run func(text string) (*model.UserAgreement, error)) *MockUserAgreementDatabase_Save_Call {
	_c.Call.Return(run)
	return _c
}
