template: testify
packages:
  college-graduation-project-backend/internal/service:
    config:
      all: true
      dir: "internal/mocks"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      pkgname: "mocks"
      structname: "{{.Mock}}{{.InterfaceName}}"

  college-graduation-project-backend/internal/database:
    config:
      all: true
      dir: "internal/mocks"
      filename: "mock_{{ .InterfaceName | snakecase }}.go"
      pkgname: "mocks"
      structname: "{{.Mock}}{{.InterfaceName}}"
