// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"college-graduation-project-backend/internal/model"
	"college-graduation-project-backend/internal/model/request"
	"college-graduation-project-backend/internal/model/response"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserService
func (_mock *MockUserService) Create(user *model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *model.User
func (_e *MockUserService_Expecter) Create(user interface{}) *MockUserService_Create_Call {
	return &MockUserService_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUserService_Create_Call) Run(run func(user *model.User)) *MockUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_Create_Call) Return(err error) *MockUserService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Create_Call) RunAndReturn(run func(user *model.User) error) *MockUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserService
func (_mock *MockUserService) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockUserService_Expecter) Delete(id interface{}) *MockUserService_Delete_Call {
	return &MockUserService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockUserService_Delete_Call) Run(run func(id uint64)) *MockUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_Delete_Call) Return(err error) *MockUserService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Delete_Call) RunAndReturn(run func(id uint64) error) *MockUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockUserService
func (_mock *MockUserService) FindAll() ([]model.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockUserService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockUserService_Expecter) FindAll() *MockUserService_FindAll_Call {
	return &MockUserService_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockUserService_FindAll_Call) Run(run func()) *MockUserService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserService_FindAll_Call) Return(users []model.User, err error) *MockUserService_FindAll_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserService_FindAll_Call) RunAndReturn(run func() ([]model.User, error)) *MockUserService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserService
func (_mock *MockUserService) FindByEmail(email string) (*model.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserService_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserService_Expecter) FindByEmail(email interface{}) *MockUserService_FindByEmail_Call {
	return &MockUserService_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *MockUserService_FindByEmail_Call) Run(run func(email string)) *MockUserService_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_FindByEmail_Call) Return(user *model.User, err error) *MockUserService_FindByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_FindByEmail_Call) RunAndReturn(run func(email string) (*model.User, error)) *MockUserService_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserService
func (_mock *MockUserService) FindByID(id uint64) (*model.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockUserService_Expecter) FindByID(id interface{}) *MockUserService_FindByID_Call {
	return &MockUserService_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockUserService_FindByID_Call) Run(run func(id uint64)) *MockUserService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_FindByID_Call) Return(user *model.User, err error) *MockUserService_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_FindByID_Call) RunAndReturn(run func(id uint64) (*model.User, error)) *MockUserService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserService
func (_mock *MockUserService) Update(user *model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *model.User
func (_e *MockUserService_Expecter) Update(user interface{}) *MockUserService_Update_Call {
	return &MockUserService_Update_Call{Call: _e.mock.On("Update", user)}
}

func (_c *MockUserService_Update_Call) Run(run func(user *model.User)) *MockUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_Update_Call) Return(err error) *MockUserService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Update_Call) RunAndReturn(run func(user *model.User) error) *MockUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockUserService
func (_mock *MockUserService) UpdateProfile(userID uint64, updateProfile request.UpdateProfile) (*model.User, error) {
	ret := _mock.Called(userID, updateProfile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, request.UpdateProfile) (*model.User, error)); ok {
		return returnFunc(userID, updateProfile)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, request.UpdateProfile) *model.User); ok {
		r0 = returnFunc(userID, updateProfile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, request.UpdateProfile) error); ok {
		r1 = returnFunc(userID, updateProfile)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - userID uint64
//   - updateProfile request.UpdateProfile
func (_e *MockUserService_Expecter) UpdateProfile(userID interface{}, updateProfile interface{}) *MockUserService_UpdateProfile_Call {
	return &MockUserService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", userID, updateProfile)}
}

func (_c *MockUserService_UpdateProfile_Call) Run(run func(userID uint64, updateProfile request.UpdateProfile)) *MockUserService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 request.UpdateProfile
		if args[1] != nil {
			arg1 = args[1].(request.UpdateProfile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_UpdateProfile_Call) Return(user *model.User, err error) *MockUserService_UpdateProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_UpdateProfile_Call) RunAndReturn(run func(userID uint64, updateProfile request.UpdateProfile) (*model.User, error)) *MockUserService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(req *request.Login) (string, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*request.Login) (string, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*request.Login) string); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*request.Login) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - req *request.Login
func (_e *MockAuthService_Expecter) Login(req interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", req)}
}

func (_c *MockAuthService_Login_Call) Run(run func(req *request.Login)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *request.Login
		if args[0] != nil {
			arg0 = args[0].(*request.Login)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(s string, err error) *MockAuthService_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(req *request.Login) (string, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(req *request.Register) (string, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*request.Register) (string, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*request.Register) string); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*request.Register) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - req *request.Register
func (_e *MockAuthService_Expecter) Register(req interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", req)}
}

func (_c *MockAuthService_Register_Call) Run(run func(req *request.Register)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *request.Register
		if args[0] != nil {
			arg0 = args[0].(*request.Register)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(s string, err error) *MockAuthService_Register_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(req *request.Register) (string, error)) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHallService creates a new instance of MockHallService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHallService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHallService {
	mock := &MockHallService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHallService is an autogenerated mock type for the HallService type
type MockHallService struct {
	mock.Mock
}

type MockHallService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHallService) EXPECT() *MockHallService_Expecter {
	return &MockHallService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockHallService
func (_mock *MockHallService) Create(userID uint64, hallCreate *request.HallCreate) (*model.Hall, error) {
	ret := _mock.Called(userID, hallCreate)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *request.HallCreate) (*model.Hall, error)); ok {
		return returnFunc(userID, hallCreate)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *request.HallCreate) *model.Hall); ok {
		r0 = returnFunc(userID, hallCreate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *request.HallCreate) error); ok {
		r1 = returnFunc(userID, hallCreate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHallService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userID uint64
//   - hallCreate *request.HallCreate
func (_e *MockHallService_Expecter) Create(userID interface{}, hallCreate interface{}) *MockHallService_Create_Call {
	return &MockHallService_Create_Call{Call: _e.mock.On("Create", userID, hallCreate)}
}

func (_c *MockHallService_Create_Call) Run(run func(userID uint64, hallCreate *request.HallCreate)) *MockHallService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *request.HallCreate
		if args[1] != nil {
			arg1 = args[1].(*request.HallCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHallService_Create_Call) Return(hall *model.Hall, err error) *MockHallService_Create_Call {
	_c.Call.Return(hall, err)
	return _c
}

func (_c *MockHallService_Create_Call) RunAndReturn(run func(userID uint64, hallCreate *request.HallCreate) (*model.Hall, error)) *MockHallService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockHallService
func (_mock *MockHallService) Delete(userID uint64, id uint64) error {
	ret := _mock.Called(userID, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = returnFunc(userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHallService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHallService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
func (_e *MockHallService_Expecter) Delete(userID interface{}, id interface{}) *MockHallService_Delete_Call {
	return &MockHallService_Delete_Call{Call: _e.mock.On("Delete", userID, id)}
}

func (_c *MockHallService_Delete_Call) Run(run func(userID uint64, id uint64)) *MockHallService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHallService_Delete_Call) Return(err error) *MockHallService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHallService_Delete_Call) RunAndReturn(run func(userID uint64, id uint64) error) *MockHallService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockHallService
func (_mock *MockHallService) FindAll() ([]model.Hall, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Hall, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Hall); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockHallService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
func (_e *MockHallService_Expecter) FindAll() *MockHallService_FindAll_Call {
	return &MockHallService_FindAll_Call{Call: _e.mock.On("FindAll")}
}

func (_c *MockHallService_FindAll_Call) Run(run func()) *MockHallService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHallService_FindAll_Call) Return(halls []model.Hall, err error) *MockHallService_FindAll_Call {
	_c.Call.Return(halls, err)
	return _c
}

func (_c *MockHallService_FindAll_Call) RunAndReturn(run func() ([]model.Hall, error)) *MockHallService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllActive provides a mock function for the type MockHallService
func (_mock *MockHallService) FindAllActive() ([]model.Hall, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindAllActive")
	}

	var r0 []model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Hall, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Hall); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_FindAllActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllActive'
type MockHallService_FindAllActive_Call struct {
	*mock.Call
}

// FindAllActive is a helper method to define mock.On call
func (_e *MockHallService_Expecter) FindAllActive() *MockHallService_FindAllActive_Call {
	return &MockHallService_FindAllActive_Call{Call: _e.mock.On("FindAllActive")}
}

func (_c *MockHallService_FindAllActive_Call) Run(run func()) *MockHallService_FindAllActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHallService_FindAllActive_Call) Return(halls []model.Hall, err error) *MockHallService_FindAllActive_Call {
	_c.Call.Return(halls, err)
	return _c
}

func (_c *MockHallService_FindAllActive_Call) RunAndReturn(run func() ([]model.Hall, error)) *MockHallService_FindAllActive_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockHallService
func (_mock *MockHallService) FindByID(id uint64) (*model.Hall, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Hall, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Hall); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHallService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockHallService_Expecter) FindByID(id interface{}) *MockHallService_FindByID_Call {
	return &MockHallService_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockHallService_FindByID_Call) Run(run func(id uint64)) *MockHallService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHallService_FindByID_Call) Return(hall *model.Hall, err error) *MockHallService_FindByID_Call {
	_c.Call.Return(hall, err)
	return _c
}

func (_c *MockHallService_FindByID_Call) RunAndReturn(run func(id uint64) (*model.Hall, error)) *MockHallService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailability provides a mock function for the type MockHallService
func (_mock *MockHallService) GetAvailability(hallID uint64, from time.Time, to time.Time) ([]response.HallAvailability, error) {
	ret := _mock.Called(hallID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailability")
	}

	var r0 []response.HallAvailability
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) ([]response.HallAvailability, error)); ok {
		return returnFunc(hallID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) []response.HallAvailability); ok {
		r0 = returnFunc(hallID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.HallAvailability)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time) error); ok {
		r1 = returnFunc(hallID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_GetAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailability'
type MockHallService_GetAvailability_Call struct {
	*mock.Call
}

// GetAvailability is a helper method to define mock.On call
//   - hallID uint64
//   - from time.Time
//   - to time.Time
func (_e *MockHallService_Expecter) GetAvailability(hallID interface{}, from interface{}, to interface{}) *MockHallService_GetAvailability_Call {
	return &MockHallService_GetAvailability_Call{Call: _e.mock.On("GetAvailability", hallID, from, to)}
}

func (_c *MockHallService_GetAvailability_Call) Run(run func(hallID uint64, from time.Time, to time.Time)) *MockHallService_GetAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHallService_GetAvailability_Call) Return(hallAvailabilitys []response.HallAvailability, err error) *MockHallService_GetAvailability_Call {
	_c.Call.Return(hallAvailabilitys, err)
	return _c
}

func (_c *MockHallService_GetAvailability_Call) RunAndReturn(run func(hallID uint64, from time.Time, to time.Time) ([]response.HallAvailability, error)) *MockHallService_GetAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockHallService
func (_mock *MockHallService) Update(userID uint64, id uint64, hallUpdate *request.HallUpdate) (*model.Hall, error) {
	ret := _mock.Called(userID, id, hallUpdate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Hall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.HallUpdate) (*model.Hall, error)); ok {
		return returnFunc(userID, id, hallUpdate)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.HallUpdate) *model.Hall); ok {
		r0 = returnFunc(userID, id, hallUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Hall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, *request.HallUpdate) error); ok {
		r1 = returnFunc(userID, id, hallUpdate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHallService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHallService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
//   - hallUpdate *request.HallUpdate
func (_e *MockHallService_Expecter) Update(userID interface{}, id interface{}, hallUpdate interface{}) *MockHallService_Update_Call {
	return &MockHallService_Update_Call{Call: _e.mock.On("Update", userID, id, hallUpdate)}
}

func (_c *MockHallService_Update_Call) Run(run func(userID uint64, id uint64, hallUpdate *request.HallUpdate)) *MockHallService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *request.HallUpdate
		if args[2] != nil {
			arg2 = args[2].(*request.HallUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockHallService_Update_Call) Return(hall *model.Hall, err error) *MockHallService_Update_Call {
	_c.Call.Return(hall, err)
	return _c
}

func (_c *MockHallService_Update_Call) RunAndReturn(run func(userID uint64, id uint64, hallUpdate *request.HallUpdate) (*model.Hall, error)) *MockHallService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageService creates a new instance of MockImageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageService {
	mock := &MockImageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageService is an autogenerated mock type for the ImageService type
type MockImageService struct {
	mock.Mock
}

type MockImageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageService) EXPECT() *MockImageService_Expecter {
	return &MockImageService_Expecter{mock: &_m.Mock}
}

// DeleteUserAvatar provides a mock function for the type MockImageService
func (_mock *MockImageService) DeleteUserAvatar(userID uint64) error {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserAvatar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_DeleteUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserAvatar'
type MockImageService_DeleteUserAvatar_Call struct {
	*mock.Call
}

// DeleteUserAvatar is a helper method to define mock.On call
//   - userID uint64
func (_e *MockImageService_Expecter) DeleteUserAvatar(userID interface{}) *MockImageService_DeleteUserAvatar_Call {
	return &MockImageService_DeleteUserAvatar_Call{Call: _e.mock.On("DeleteUserAvatar", userID)}
}

func (_c *MockImageService_DeleteUserAvatar_Call) Run(run func(userID uint64)) *MockImageService_DeleteUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_DeleteUserAvatar_Call) Return(err error) *MockImageService_DeleteUserAvatar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_DeleteUserAvatar_Call) RunAndReturn(run func(userID uint64) error) *MockImageService_DeleteUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// GetHallImages provides a mock function for the type MockImageService
func (_mock *MockImageService) GetHallImages(hallID uint64) ([]string, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for GetHallImages")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) ([]string, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) []string); ok {
		r0 = returnFunc(hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetHallImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHallImages'
type MockImageService_GetHallImages_Call struct {
	*mock.Call
}

// GetHallImages is a helper method to define mock.On call
//   - hallID uint64
func (_e *MockImageService_Expecter) GetHallImages(hallID interface{}) *MockImageService_GetHallImages_Call {
	return &MockImageService_GetHallImages_Call{Call: _e.mock.On("GetHallImages", hallID)}
}

func (_c *MockImageService_GetHallImages_Call) Run(run func(hallID uint64)) *MockImageService_GetHallImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_GetHallImages_Call) Return(strings []string, err error) *MockImageService_GetHallImages_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockImageService_GetHallImages_Call) RunAndReturn(run func(hallID uint64) ([]string, error)) *MockImageService_GetHallImages_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAvatar provides a mock function for the type MockImageService
func (_mock *MockImageService) GetUserAvatar(userID uint64) (*string, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAvatar")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*string, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *string); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageService_GetUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAvatar'
type MockImageService_GetUserAvatar_Call struct {
	*mock.Call
}

// GetUserAvatar is a helper method to define mock.On call
//   - userID uint64
func (_e *MockImageService_Expecter) GetUserAvatar(userID interface{}) *MockImageService_GetUserAvatar_Call {
	return &MockImageService_GetUserAvatar_Call{Call: _e.mock.On("GetUserAvatar", userID)}
}

func (_c *MockImageService_GetUserAvatar_Call) Run(run func(userID uint64)) *MockImageService_GetUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockImageService_GetUserAvatar_Call) Return(s *string, err error) *MockImageService_GetUserAvatar_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockImageService_GetUserAvatar_Call) RunAndReturn(run func(userID uint64) (*string, error)) *MockImageService_GetUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserAvatar provides a mock function for the type MockImageService
func (_mock *MockImageService) SetUserAvatar(userID uint64, imagePath string) error {
	ret := _mock.Called(userID, imagePath)

	if len(ret) == 0 {
		panic("no return value specified for SetUserAvatar")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, string) error); ok {
		r0 = returnFunc(userID, imagePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_SetUserAvatar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserAvatar'
type MockImageService_SetUserAvatar_Call struct {
	*mock.Call
}

// SetUserAvatar is a helper method to define mock.On call
//   - userID uint64
//   - imagePath string
func (_e *MockImageService_Expecter) SetUserAvatar(userID interface{}, imagePath interface{}) *MockImageService_SetUserAvatar_Call {
	return &MockImageService_SetUserAvatar_Call{Call: _e.mock.On("SetUserAvatar", userID, imagePath)}
}

func (_c *MockImageService_SetUserAvatar_Call) Run(run func(userID uint64, imagePath string)) *MockImageService_SetUserAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageService_SetUserAvatar_Call) Return(err error) *MockImageService_SetUserAvatar_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_SetUserAvatar_Call) RunAndReturn(run func(userID uint64, imagePath string) error) *MockImageService_SetUserAvatar_Call {
	_c.Call.Return(run)
	return _c
}

// UploadHallImage provides a mock function for the type MockImageService
func (_mock *MockImageService) UploadHallImage(userID uint64, hallID uint64, imagePath string) error {
	ret := _mock.Called(userID, hallID, imagePath)

	if len(ret) == 0 {
		panic("no return value specified for UploadHallImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, string) error); ok {
		r0 = returnFunc(userID, hallID, imagePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageService_UploadHallImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadHallImage'
type MockImageService_UploadHallImage_Call struct {
	*mock.Call
}

// UploadHallImage is a helper method to define mock.On call
//   - userID uint64
//   - hallID uint64
//   - imagePath string
func (_e *MockImageService_Expecter) UploadHallImage(userID interface{}, hallID interface{}, imagePath interface{}) *MockImageService_UploadHallImage_Call {
	return &MockImageService_UploadHallImage_Call{Call: _e.mock.On("UploadHallImage", userID, hallID, imagePath)}
}

func (_c *MockImageService_UploadHallImage_Call) Run(run func(userID uint64, hallID uint64, imagePath string)) *MockImageService_UploadHallImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageService_UploadHallImage_Call) Return(err error) *MockImageService_UploadHallImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageService_UploadHallImage_Call) RunAndReturn(run func(userID uint64, hallID uint64, imagePath string) error) *MockImageService_UploadHallImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingService creates a new instance of MockBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingService {
	mock := &MockBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingService is an autogenerated mock type for the BookingService type
type MockBookingService struct {
	mock.Mock
}

type MockBookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingService) EXPECT() *MockBookingService_Expecter {
	return &MockBookingService_Expecter{mock: &_m.Mock}
}

// CalculatePrice provides a mock function for the type MockBookingService
func (_mock *MockBookingService) CalculatePrice(hallID uint64, from time.Time, to time.Time) (*response.CalculatedPrice, error) {
	ret := _mock.Called(hallID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for CalculatePrice")
	}

	var r0 *response.CalculatedPrice
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) (*response.CalculatedPrice, error)); ok {
		return returnFunc(hallID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time) *response.CalculatedPrice); ok {
		r0 = returnFunc(hallID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.CalculatedPrice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time) error); ok {
		r1 = returnFunc(hallID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_CalculatePrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculatePrice'
type MockBookingService_CalculatePrice_Call struct {
	*mock.Call
}

// CalculatePrice is a helper method to define mock.On call
//   - hallID uint64
//   - from time.Time
//   - to time.Time
func (_e *MockBookingService_Expecter) CalculatePrice(hallID interface{}, from interface{}, to interface{}) *MockBookingService_CalculatePrice_Call {
	return &MockBookingService_CalculatePrice_Call{Call: _e.mock.On("CalculatePrice", hallID, from, to)}
}

func (_c *MockBookingService_CalculatePrice_Call) Run(run func(hallID uint64, from time.Time, to time.Time)) *MockBookingService_CalculatePrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingService_CalculatePrice_Call) Return(calculatedPrice *response.CalculatedPrice, err error) *MockBookingService_CalculatePrice_Call {
	_c.Call.Return(calculatedPrice, err)
	return _c
}

func (_c *MockBookingService_CalculatePrice_Call) RunAndReturn(run func(hallID uint64, from time.Time, to time.Time) (*response.CalculatedPrice, error)) *MockBookingService_CalculatePrice_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingService
func (_mock *MockBookingService) Create(userID uint64, req *request.BookingCreate) (*model.Booking, error) {
	ret := _mock.Called(userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *request.BookingCreate) (*model.Booking, error)); ok {
		return returnFunc(userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *request.BookingCreate) *model.Booking); ok {
		r0 = returnFunc(userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *request.BookingCreate) error); ok {
		r1 = returnFunc(userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userID uint64
//   - req *request.BookingCreate
func (_e *MockBookingService_Expecter) Create(userID interface{}, req interface{}) *MockBookingService_Create_Call {
	return &MockBookingService_Create_Call{Call: _e.mock.On("Create", userID, req)}
}

func (_c *MockBookingService_Create_Call) Run(run func(userID uint64, req *request.BookingCreate)) *MockBookingService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *request.BookingCreate
		if args[1] != nil {
			arg1 = args[1].(*request.BookingCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingService_Create_Call) Return(booking *model.Booking, err error) *MockBookingService_Create_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingService_Create_Call) RunAndReturn(run func(userID uint64, req *request.BookingCreate) (*model.Booking, error)) *MockBookingService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByAuthor provides a mock function for the type MockBookingService
func (_mock *MockBookingService) DeleteByAuthor(userID uint64, id uint64) error {
	ret := _mock.Called(userID, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByAuthor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) error); ok {
		r0 = returnFunc(userID, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBookingService_DeleteByAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByAuthor'
type MockBookingService_DeleteByAuthor_Call struct {
	*mock.Call
}

// DeleteByAuthor is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
func (_e *MockBookingService_Expecter) DeleteByAuthor(userID interface{}, id interface{}) *MockBookingService_DeleteByAuthor_Call {
	return &MockBookingService_DeleteByAuthor_Call{Call: _e.mock.On("DeleteByAuthor", userID, id)}
}

func (_c *MockBookingService_DeleteByAuthor_Call) Run(run func(userID uint64, id uint64)) *MockBookingService_DeleteByAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingService_DeleteByAuthor_Call) Return(err error) *MockBookingService_DeleteByAuthor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBookingService_DeleteByAuthor_Call) RunAndReturn(run func(userID uint64, id uint64) error) *MockBookingService_DeleteByAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockBookingService
func (_mock *MockBookingService) FindAll(userID uint64, hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time) ([]model.Booking, error) {
	ret := _mock.Called(userID, hallID, bookingUserID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *uint64, *uint64, *time.Time, *time.Time) ([]model.Booking, error)); ok {
		return returnFunc(userID, hallID, bookingUserID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *uint64, *uint64, *time.Time, *time.Time) []model.Booking); ok {
		r0 = returnFunc(userID, hallID, bookingUserID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *uint64, *uint64, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(userID, hallID, bookingUserID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBookingService_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - userID uint64
//   - hallID *uint64
//   - bookingUserID *uint64
//   - from *time.Time
//   - to *time.Time
func (_e *MockBookingService_Expecter) FindAll(userID interface{}, hallID interface{}, bookingUserID interface{}, from interface{}, to interface{}) *MockBookingService_FindAll_Call {
	return &MockBookingService_FindAll_Call{Call: _e.mock.On("FindAll", userID, hallID, bookingUserID, from, to)}
}

func (_c *MockBookingService_FindAll_Call) Run(run func(userID uint64, hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time)) *MockBookingService_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		var arg2 *uint64
		if args[2] != nil {
			arg2 = args[2].(*uint64)
		}
		var arg3 *time.Time
		if args[3] != nil {
			arg3 = args[3].(*time.Time)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBookingService_FindAll_Call) Return(bookings []model.Booking, err error) *MockBookingService_FindAll_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingService_FindAll_Call) RunAndReturn(run func(userID uint64, hallID *uint64, bookingUserID *uint64, from *time.Time, to *time.Time) ([]model.Booking, error)) *MockBookingService_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllFromUser provides a mock function for the type MockBookingService
func (_mock *MockBookingService) FindAllFromUser(userID uint64, from *time.Time, to *time.Time) ([]model.Booking, error) {
	ret := _mock.Called(userID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for FindAllFromUser")
	}

	var r0 []model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, *time.Time, *time.Time) ([]model.Booking, error)); ok {
		return returnFunc(userID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, *time.Time, *time.Time) []model.Booking); ok {
		r0 = returnFunc(userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, *time.Time, *time.Time) error); ok {
		r1 = returnFunc(userID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_FindAllFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllFromUser'
type MockBookingService_FindAllFromUser_Call struct {
	*mock.Call
}

// FindAllFromUser is a helper method to define mock.On call
//   - userID uint64
//   - from *time.Time
//   - to *time.Time
func (_e *MockBookingService_Expecter) FindAllFromUser(userID interface{}, from interface{}, to interface{}) *MockBookingService_FindAllFromUser_Call {
	return &MockBookingService_FindAllFromUser_Call{Call: _e.mock.On("FindAllFromUser", userID, from, to)}
}

func (_c *MockBookingService_FindAllFromUser_Call) Run(run func(userID uint64, from *time.Time, to *time.Time)) *MockBookingService_FindAllFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *time.Time
		if args[1] != nil {
			arg1 = args[1].(*time.Time)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingService_FindAllFromUser_Call) Return(bookings []model.Booking, err error) *MockBookingService_FindAllFromUser_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingService_FindAllFromUser_Call) RunAndReturn(run func(userID uint64, from *time.Time, to *time.Time) ([]model.Booking, error)) *MockBookingService_FindAllFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockBookingService
func (_mock *MockBookingService) FindByID(userID uint64, id uint64) (*model.Booking, error) {
	ret := _mock.Called(userID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*model.Booking, error)); ok {
		return returnFunc(userID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *model.Booking); ok {
		r0 = returnFunc(userID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = returnFunc(userID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBookingService_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
func (_e *MockBookingService_Expecter) FindByID(userID interface{}, id interface{}) *MockBookingService_FindByID_Call {
	return &MockBookingService_FindByID_Call{Call: _e.mock.On("FindByID", userID, id)}
}

func (_c *MockBookingService_FindByID_Call) Run(run func(userID uint64, id uint64)) *MockBookingService_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingService_FindByID_Call) Return(booking *model.Booking, err error) *MockBookingService_FindByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingService_FindByID_Call) RunAndReturn(run func(userID uint64, id uint64) (*model.Booking, error)) *MockBookingService_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBookingService
func (_mock *MockBookingService) Update(userID uint64, id uint64, req *request.BookingUpdate) (*model.Booking, error) {
	ret := _mock.Called(userID, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.BookingUpdate) (*model.Booking, error)); ok {
		return returnFunc(userID, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.BookingUpdate) *model.Booking); ok {
		r0 = returnFunc(userID, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, *request.BookingUpdate) error); ok {
		r1 = returnFunc(userID, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBookingService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID uint64
//   - id uint64
//   - req *request.BookingUpdate
func (_e *MockBookingService_Expecter) Update(userID interface{}, id interface{}, req interface{}) *MockBookingService_Update_Call {
	return &MockBookingService_Update_Call{Call: _e.mock.On("Update", userID, id, req)}
}

func (_c *MockBookingService_Update_Call) Run(run func(userID uint64, id uint64, req *request.BookingUpdate)) *MockBookingService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *request.BookingUpdate
		if args[2] != nil {
			arg2 = args[2].(*request.BookingUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingService_Update_Call) Return(booking *model.Booking, err error) *MockBookingService_Update_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingService_Update_Call) RunAndReturn(run func(userID uint64, id uint64, req *request.BookingUpdate) (*model.Booking, error)) *MockBookingService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReviewService creates a new instance of MockReviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReviewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReviewService {
	mock := &MockReviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReviewService is an autogenerated mock type for the ReviewService type
type MockReviewService struct {
	mock.Mock
}

type MockReviewService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReviewService) EXPECT() *MockReviewService_Expecter {
	return &MockReviewService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReviewService
func (_mock *MockReviewService) Create(userID uint64, bookingID uint64, req *request.ReviewCreate) (*model.Review, error) {
	ret := _mock.Called(userID, bookingID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.ReviewCreate) (*model.Review, error)); ok {
		return returnFunc(userID, bookingID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.ReviewCreate) *model.Review); ok {
		r0 = returnFunc(userID, bookingID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, *request.ReviewCreate) error); ok {
		r1 = returnFunc(userID, bookingID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReviewService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - userID uint64
//   - bookingID uint64
//   - req *request.ReviewCreate
func (_e *MockReviewService_Expecter) Create(userID interface{}, bookingID interface{}, req interface{}) *MockReviewService_Create_Call {
	return &MockReviewService_Create_Call{Call: _e.mock.On("Create", userID, bookingID, req)}
}

func (_c *MockReviewService_Create_Call) Run(run func(userID uint64, bookingID uint64, req *request.ReviewCreate)) *MockReviewService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *request.ReviewCreate
		if args[2] != nil {
			arg2 = args[2].(*request.ReviewCreate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReviewService_Create_Call) Return(review *model.Review, err error) *MockReviewService_Create_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewService_Create_Call) RunAndReturn(run func(userID uint64, bookingID uint64, req *request.ReviewCreate) (*model.Review, error)) *MockReviewService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockReviewService
func (_mock *MockReviewService) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReviewService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReviewService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockReviewService_Expecter) Delete(id interface{}) *MockReviewService_Delete_Call {
	return &MockReviewService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockReviewService_Delete_Call) Run(run func(id uint64)) *MockReviewService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewService_Delete_Call) Return(err error) *MockReviewService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReviewService_Delete_Call) RunAndReturn(run func(id uint64) error) *MockReviewService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllWithFilters provides a mock function for the type MockReviewService
func (_mock *MockReviewService) GetAllWithFilters(hallID *uint64, minRating *uint64) ([]model.Review, error) {
	ret := _mock.Called(hallID, minRating)

	if len(ret) == 0 {
		panic("no return value specified for GetAllWithFilters")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) ([]model.Review, error)); ok {
		return returnFunc(hallID, minRating)
	}
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) []model.Review); ok {
		r0 = returnFunc(hallID, minRating)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*uint64, *uint64) error); ok {
		r1 = returnFunc(hallID, minRating)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_GetAllWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllWithFilters'
type MockReviewService_GetAllWithFilters_Call struct {
	*mock.Call
}

// GetAllWithFilters is a helper method to define mock.On call
//   - hallID *uint64
//   - minRating *uint64
func (_e *MockReviewService_Expecter) GetAllWithFilters(hallID interface{}, minRating interface{}) *MockReviewService_GetAllWithFilters_Call {
	return &MockReviewService_GetAllWithFilters_Call{Call: _e.mock.On("GetAllWithFilters", hallID, minRating)}
}

func (_c *MockReviewService_GetAllWithFilters_Call) Run(run func(hallID *uint64, minRating *uint64)) *MockReviewService_GetAllWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *uint64
		if args[0] != nil {
			arg0 = args[0].(*uint64)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewService_GetAllWithFilters_Call) Return(reviews []model.Review, err error) *MockReviewService_GetAllWithFilters_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewService_GetAllWithFilters_Call) RunAndReturn(run func(hallID *uint64, minRating *uint64) ([]model.Review, error)) *MockReviewService_GetAllWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetByBookingID provides a mock function for the type MockReviewService
func (_mock *MockReviewService) GetByBookingID(userID uint64, bookingID uint64) (*model.Review, error) {
	ret := _mock.Called(userID, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for GetByBookingID")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*model.Review, error)); ok {
		return returnFunc(userID, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *model.Review); ok {
		r0 = returnFunc(userID, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = returnFunc(userID, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_GetByBookingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByBookingID'
type MockReviewService_GetByBookingID_Call struct {
	*mock.Call
}

// GetByBookingID is a helper method to define mock.On call
//   - userID uint64
//   - bookingID uint64
func (_e *MockReviewService_Expecter) GetByBookingID(userID interface{}, bookingID interface{}) *MockReviewService_GetByBookingID_Call {
	return &MockReviewService_GetByBookingID_Call{Call: _e.mock.On("GetByBookingID", userID, bookingID)}
}

func (_c *MockReviewService_GetByBookingID_Call) Run(run func(userID uint64, bookingID uint64)) *MockReviewService_GetByBookingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReviewService_GetByBookingID_Call) Return(review *model.Review, err error) *MockReviewService_GetByBookingID_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewService_GetByBookingID_Call) RunAndReturn(run func(userID uint64, bookingID uint64) (*model.Review, error)) *MockReviewService_GetByBookingID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHallID provides a mock function for the type MockReviewService
func (_mock *MockReviewService) GetByHallID(hallID uint64) ([]model.Review, error) {
	ret := _mock.Called(hallID)

	if len(ret) == 0 {
		panic("no return value specified for GetByHallID")
	}

	var r0 []model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) ([]model.Review, error)); ok {
		return returnFunc(hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) []model.Review); ok {
		r0 = returnFunc(hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_GetByHallID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHallID'
type MockReviewService_GetByHallID_Call struct {
	*mock.Call
}

// GetByHallID is a helper method to define mock.On call
//   - hallID uint64
func (_e *MockReviewService_Expecter) GetByHallID(hallID interface{}) *MockReviewService_GetByHallID_Call {
	return &MockReviewService_GetByHallID_Call{Call: _e.mock.On("GetByHallID", hallID)}
}

func (_c *MockReviewService_GetByHallID_Call) Run(run func(hallID uint64)) *MockReviewService_GetByHallID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReviewService_GetByHallID_Call) Return(reviews []model.Review, err error) *MockReviewService_GetByHallID_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockReviewService_GetByHallID_Call) RunAndReturn(run func(hallID uint64) ([]model.Review, error)) *MockReviewService_GetByHallID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockReviewService
func (_mock *MockReviewService) Update(userID uint64, reviewID uint64, req *request.ReviewCreate) (*model.Review, error) {
	ret := _mock.Called(userID, reviewID, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.ReviewCreate) (*model.Review, error)); ok {
		return returnFunc(userID, reviewID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, *request.ReviewCreate) *model.Review); ok {
		r0 = returnFunc(userID, reviewID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, *request.ReviewCreate) error); ok {
		r1 = returnFunc(userID, reviewID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReviewService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockReviewService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID uint64
//   - reviewID uint64
//   - req *request.ReviewCreate
func (_e *MockReviewService_Expecter) Update(userID interface{}, reviewID interface{}, req interface{}) *MockReviewService_Update_Call {
	return &MockReviewService_Update_Call{Call: _e.mock.On("Update", userID, reviewID, req)}
}

func (_c *MockReviewService_Update_Call) Run(run func(userID uint64, reviewID uint64, req *request.ReviewCreate)) *MockReviewService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *request.ReviewCreate
		if args[2] != nil {
			arg2 = args[2].(*request.ReviewCreate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReviewService_Update_Call) Return(review *model.Review, err error) *MockReviewService_Update_Call {
	_c.Call.Return(review, err)
	return _c
}

func (_c *MockReviewService_Update_Call) RunAndReturn(run func(userID uint64, reviewID uint64, req *request.ReviewCreate) (*model.Review, error)) *MockReviewService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportService creates a new instance of MockReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportService {
	mock := &MockReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportService is an autogenerated mock type for the ReportService type
type MockReportService struct {
	mock.Mock
}

type MockReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportService) EXPECT() *MockReportService_Expecter {
	return &MockReportService_Expecter{mock: &_m.Mock}
}

// GetBookingsDynamicsReport provides a mock function for the type MockReportService
func (_mock *MockReportService) GetBookingsDynamicsReport(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string) (*response.BookingsDynamicsReport, error) {
	ret := _mock.Called(userID, from, to, hallID, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsDynamicsReport")
	}

	var r0 *response.BookingsDynamicsReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string) (*response.BookingsDynamicsReport, error)); ok {
		return returnFunc(userID, from, to, hallID, groupBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string) *response.BookingsDynamicsReport); ok {
		r0 = returnFunc(userID, from, to, hallID, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.BookingsDynamicsReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, string) error); ok {
		r1 = returnFunc(userID, from, to, hallID, groupBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetBookingsDynamicsReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsDynamicsReport'
type MockReportService_GetBookingsDynamicsReport_Call struct {
	*mock.Call
}

// GetBookingsDynamicsReport is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - groupBy string
func (_e *MockReportService_Expecter) GetBookingsDynamicsReport(userID interface{}, from interface{}, to interface{}, hallID interface{}, groupBy interface{}) *MockReportService_GetBookingsDynamicsReport_Call {
	return &MockReportService_GetBookingsDynamicsReport_Call{Call: _e.mock.On("GetBookingsDynamicsReport", userID, from, to, hallID, groupBy)}
}

func (_c *MockReportService_GetBookingsDynamicsReport_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string)) *MockReportService_GetBookingsDynamicsReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReportService_GetBookingsDynamicsReport_Call) Return(bookingsDynamicsReport *response.BookingsDynamicsReport, err error) *MockReportService_GetBookingsDynamicsReport_Call {
	_c.Call.Return(bookingsDynamicsReport, err)
	return _c
}

func (_c *MockReportService_GetBookingsDynamicsReport_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string) (*response.BookingsDynamicsReport, error)) *MockReportService_GetBookingsDynamicsReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsDynamicsReportPDF provides a mock function for the type MockReportService
func (_mock *MockReportService) GetBookingsDynamicsReportPDF(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string) ([]byte, error) {
	ret := _mock.Called(userID, from, to, hallID, groupBy)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsDynamicsReportPDF")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string) ([]byte, error)); ok {
		return returnFunc(userID, from, to, hallID, groupBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string) []byte); ok {
		r0 = returnFunc(userID, from, to, hallID, groupBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, string) error); ok {
		r1 = returnFunc(userID, from, to, hallID, groupBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetBookingsDynamicsReportPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsDynamicsReportPDF'
type MockReportService_GetBookingsDynamicsReportPDF_Call struct {
	*mock.Call
}

// GetBookingsDynamicsReportPDF is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - groupBy string
func (_e *MockReportService_Expecter) GetBookingsDynamicsReportPDF(userID interface{}, from interface{}, to interface{}, hallID interface{}, groupBy interface{}) *MockReportService_GetBookingsDynamicsReportPDF_Call {
	return &MockReportService_GetBookingsDynamicsReportPDF_Call{Call: _e.mock.On("GetBookingsDynamicsReportPDF", userID, from, to, hallID, groupBy)}
}

func (_c *MockReportService_GetBookingsDynamicsReportPDF_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string)) *MockReportService_GetBookingsDynamicsReportPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReportService_GetBookingsDynamicsReportPDF_Call) Return(bytes []byte, err error) *MockReportService_GetBookingsDynamicsReportPDF_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReportService_GetBookingsDynamicsReportPDF_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string) ([]byte, error)) *MockReportService_GetBookingsDynamicsReportPDF_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientsReport provides a mock function for the type MockReportService
func (_mock *MockReportService) GetClientsReport(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64) (*response.ClientsReport, error) {
	ret := _mock.Called(userID, from, to, hallID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetClientsReport")
	}

	var r0 *response.ClientsReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, uint64) (*response.ClientsReport, error)); ok {
		return returnFunc(userID, from, to, hallID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, uint64) *response.ClientsReport); ok {
		r0 = returnFunc(userID, from, to, hallID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ClientsReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, uint64) error); ok {
		r1 = returnFunc(userID, from, to, hallID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetClientsReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientsReport'
type MockReportService_GetClientsReport_Call struct {
	*mock.Call
}

// GetClientsReport is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - limit uint64
func (_e *MockReportService_Expecter) GetClientsReport(userID interface{}, from interface{}, to interface{}, hallID interface{}, limit interface{}) *MockReportService_GetClientsReport_Call {
	return &MockReportService_GetClientsReport_Call{Call: _e.mock.On("GetClientsReport", userID, from, to, hallID, limit)}
}

func (_c *MockReportService_GetClientsReport_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64)) *MockReportService_GetClientsReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReportService_GetClientsReport_Call) Return(clientsReport *response.ClientsReport, err error) *MockReportService_GetClientsReport_Call {
	_c.Call.Return(clientsReport, err)
	return _c
}

func (_c *MockReportService_GetClientsReport_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64) (*response.ClientsReport, error)) *MockReportService_GetClientsReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientsReportPDF provides a mock function for the type MockReportService
func (_mock *MockReportService) GetClientsReportPDF(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64) ([]byte, error) {
	ret := _mock.Called(userID, from, to, hallID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetClientsReportPDF")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, uint64) ([]byte, error)); ok {
		return returnFunc(userID, from, to, hallID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, uint64) []byte); ok {
		r0 = returnFunc(userID, from, to, hallID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, uint64) error); ok {
		r1 = returnFunc(userID, from, to, hallID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetClientsReportPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientsReportPDF'
type MockReportService_GetClientsReportPDF_Call struct {
	*mock.Call
}

// GetClientsReportPDF is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - limit uint64
func (_e *MockReportService_Expecter) GetClientsReportPDF(userID interface{}, from interface{}, to interface{}, hallID interface{}, limit interface{}) *MockReportService_GetClientsReportPDF_Call {
	return &MockReportService_GetClientsReportPDF_Call{Call: _e.mock.On("GetClientsReportPDF", userID, from, to, hallID, limit)}
}

func (_c *MockReportService_GetClientsReportPDF_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64)) *MockReportService_GetClientsReportPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockReportService_GetClientsReportPDF_Call) Return(bytes []byte, err error) *MockReportService_GetClientsReportPDF_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReportService_GetClientsReportPDF_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, limit uint64) ([]byte, error)) *MockReportService_GetClientsReportPDF_Call {
	_c.Call.Return(run)
	return _c
}

// GetHallsLoadReport provides a mock function for the type MockReportService
func (_mock *MockReportService) GetHallsLoadReport(userID uint64, from time.Time, to time.Time, hallID *uint64) (*response.HallsLoadReport, error) {
	ret := _mock.Called(userID, from, to, hallID)

	if len(ret) == 0 {
		panic("no return value specified for GetHallsLoadReport")
	}

	var r0 *response.HallsLoadReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64) (*response.HallsLoadReport, error)); ok {
		return returnFunc(userID, from, to, hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64) *response.HallsLoadReport); ok {
		r0 = returnFunc(userID, from, to, hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.HallsLoadReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64) error); ok {
		r1 = returnFunc(userID, from, to, hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetHallsLoadReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHallsLoadReport'
type MockReportService_GetHallsLoadReport_Call struct {
	*mock.Call
}

// GetHallsLoadReport is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
func (_e *MockReportService_Expecter) GetHallsLoadReport(userID interface{}, from interface{}, to interface{}, hallID interface{}) *MockReportService_GetHallsLoadReport_Call {
	return &MockReportService_GetHallsLoadReport_Call{Call: _e.mock.On("GetHallsLoadReport", userID, from, to, hallID)}
}

func (_c *MockReportService_GetHallsLoadReport_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64)) *MockReportService_GetHallsLoadReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReportService_GetHallsLoadReport_Call) Return(hallsLoadReport *response.HallsLoadReport, err error) *MockReportService_GetHallsLoadReport_Call {
	_c.Call.Return(hallsLoadReport, err)
	return _c
}

func (_c *MockReportService_GetHallsLoadReport_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64) (*response.HallsLoadReport, error)) *MockReportService_GetHallsLoadReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetHallsLoadReportPDF provides a mock function for the type MockReportService
func (_mock *MockReportService) GetHallsLoadReportPDF(userID uint64, from time.Time, to time.Time, hallID *uint64) ([]byte, error) {
	ret := _mock.Called(userID, from, to, hallID)

	if len(ret) == 0 {
		panic("no return value specified for GetHallsLoadReportPDF")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64) ([]byte, error)); ok {
		return returnFunc(userID, from, to, hallID)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64) []byte); ok {
		r0 = returnFunc(userID, from, to, hallID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64) error); ok {
		r1 = returnFunc(userID, from, to, hallID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetHallsLoadReportPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHallsLoadReportPDF'
type MockReportService_GetHallsLoadReportPDF_Call struct {
	*mock.Call
}

// GetHallsLoadReportPDF is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
func (_e *MockReportService_Expecter) GetHallsLoadReportPDF(userID interface{}, from interface{}, to interface{}, hallID interface{}) *MockReportService_GetHallsLoadReportPDF_Call {
	return &MockReportService_GetHallsLoadReportPDF_Call{Call: _e.mock.On("GetHallsLoadReportPDF", userID, from, to, hallID)}
}

func (_c *MockReportService_GetHallsLoadReportPDF_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64)) *MockReportService_GetHallsLoadReportPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockReportService_GetHallsLoadReportPDF_Call) Return(bytes []byte, err error) *MockReportService_GetHallsLoadReportPDF_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReportService_GetHallsLoadReportPDF_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64) ([]byte, error)) *MockReportService_GetHallsLoadReportPDF_Call {
	_c.Call.Return(run)
	return _c
}

// GetSalesReport provides a mock function for the type MockReportService
func (_mock *MockReportService) GetSalesReport(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string) (*response.SalesReport, error) {
	ret := _mock.Called(userID, from, to, hallID, groupBy, metrics)

	if len(ret) == 0 {
		panic("no return value specified for GetSalesReport")
	}

	var r0 *response.SalesReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string, []string) (*response.SalesReport, error)); ok {
		return returnFunc(userID, from, to, hallID, groupBy, metrics)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string, []string) *response.SalesReport); ok {
		r0 = returnFunc(userID, from, to, hallID, groupBy, metrics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.SalesReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, string, []string) error); ok {
		r1 = returnFunc(userID, from, to, hallID, groupBy, metrics)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetSalesReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSalesReport'
type MockReportService_GetSalesReport_Call struct {
	*mock.Call
}

// GetSalesReport is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - groupBy string
//   - metrics []string
func (_e *MockReportService_Expecter) GetSalesReport(userID interface{}, from interface{}, to interface{}, hallID interface{}, groupBy interface{}, metrics interface{}) *MockReportService_GetSalesReport_Call {
	return &MockReportService_GetSalesReport_Call{Call: _e.mock.On("GetSalesReport", userID, from, to, hallID, groupBy, metrics)}
}

func (_c *MockReportService_GetSalesReport_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string)) *MockReportService_GetSalesReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockReportService_GetSalesReport_Call) Return(salesReport *response.SalesReport, err error) *MockReportService_GetSalesReport_Call {
	_c.Call.Return(salesReport, err)
	return _c
}

func (_c *MockReportService_GetSalesReport_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string) (*response.SalesReport, error)) *MockReportService_GetSalesReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetSalesReportPDF provides a mock function for the type MockReportService
func (_mock *MockReportService) GetSalesReportPDF(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string) ([]byte, error) {
	ret := _mock.Called(userID, from, to, hallID, groupBy, metrics)

	if len(ret) == 0 {
		panic("no return value specified for GetSalesReportPDF")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string, []string) ([]byte, error)); ok {
		return returnFunc(userID, from, to, hallID, groupBy, metrics)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, time.Time, time.Time, *uint64, string, []string) []byte); ok {
		r0 = returnFunc(userID, from, to, hallID, groupBy, metrics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, time.Time, time.Time, *uint64, string, []string) error); ok {
		r1 = returnFunc(userID, from, to, hallID, groupBy, metrics)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReportService_GetSalesReportPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSalesReportPDF'
type MockReportService_GetSalesReportPDF_Call struct {
	*mock.Call
}

// GetSalesReportPDF is a helper method to define mock.On call
//   - userID uint64
//   - from time.Time
//   - to time.Time
//   - hallID *uint64
//   - groupBy string
//   - metrics []string
func (_e *MockReportService_Expecter) GetSalesReportPDF(userID interface{}, from interface{}, to interface{}, hallID interface{}, groupBy interface{}, metrics interface{}) *MockReportService_GetSalesReportPDF_Call {
	return &MockReportService_GetSalesReportPDF_Call{Call: _e.mock.On("GetSalesReportPDF", userID, from, to, hallID, groupBy, metrics)}
}

func (_c *MockReportService_GetSalesReportPDF_Call) Run(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string)) *MockReportService_GetSalesReportPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockReportService_GetSalesReportPDF_Call) Return(bytes []byte, err error) *MockReportService_GetSalesReportPDF_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReportService_GetSalesReportPDF_Call) RunAndReturn(run func(userID uint64, from time.Time, to time.Time, hallID *uint64, groupBy string, metrics []string) ([]byte, error)) *MockReportService_GetSalesReportPDF_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserAgreementService creates a new instance of MockUserAgreementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAgreementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAgreementService {
	mock := &MockUserAgreementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserAgreementService is an autogenerated mock type for the UserAgreementService type
type MockUserAgreementService struct {
	mock.Mock
}

type MockUserAgreementService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAgreementService) EXPECT() *MockUserAgreementService_Expecter {
	return &MockUserAgreementService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockUserAgreementService
func (_mock *MockUserAgreementService) Get() (*model.UserAgreement, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.UserAgreement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.UserAgreement, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.UserAgreement); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAgreement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAgreementService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserAgreementService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockUserAgreementService_Expecter) Get() *MockUserAgreementService_Get_Call {
	return &MockUserAgreementService_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockUserAgreementService_Get_Call) Run(run func()) *MockUserAgreementService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserAgreementService_Get_Call) Return(userAgreement *model.UserAgreement, err error) *MockUserAgreementService_Get_Call {
	_c.Call.Return(userAgreement, err)
	return _c
}

func (_c *MockUserAgreementService_Get_Call) RunAndReturn(run func() (*model.UserAgreement, error)) *MockUserAgreementService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserAgreementService
func (_mock *MockUserAgreementService) Update(userID uint64, text string) (*model.UserAgreement, error) {
	ret := _mock.Called(userID, text)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.UserAgreement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, string) (*model.UserAgreement, error)); ok {
		return returnFunc(userID, text)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, string) *model.UserAgreement); ok {
		r0 = returnFunc(userID, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAgreement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, string) error); ok {
		r1 = returnFunc(userID, text)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserAgreementService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserAgreementService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - userID uint64
//   - text string
func (_e *MockUserAgreementService_Expecter) Update(userID interface{}, text interface{}) *MockUserAgreementService_Update_Call {
	return &MockUserAgreementService_Update_Call{Call: _e.mock.On("Update", userID, text)}
}

func (_c *MockUserAgreementService_Update_Call) Run(run func(userID uint64, text string)) *MockUserAgreementService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserAgreementService_Update_Call) Return(userAgreement *model.UserAgreement, err error) *MockUserAgreementService_Update_Call {
	_c.Call.Return(userAgreement, err)
	return _c
}

func (_c *MockUserAgreementService_Update_Call) RunAndReturn(run func(userID uint64, text string) (*model.UserAgreement, error)) *MockUserAgreementService_Update_Call {
	_c.Call.Return(run)
	return _c
}
